// labels 層 (ADR-0045 / #4965): 親の管理画面 /admin/challenges。置き場所の規則は docs/DESIGN.md §6
import { adminScreenHeading } from '../admin-screens';
import { CHALLENGE_TERMS, CONCEPT_ICONS, REWARD_TERMS } from '../terms';
import { formatPeople } from './format';

// ============================================================
// admin/challenges ページ (#1452 Phase B)
// ============================================================

export const CHALLENGES_LABELS = {
	// #3239: チャレンジ一本化 (#3195/#3231: アプリ週次自動生成 + 読み取り専用ビュー) に伴い、
	// manual 作成フォーム / 一括 import 確認 UI / カテゴリ重複 (GROWTH_BOOK_LABELS と重複) の
	// dead label (参照ゼロ) を削除。残すのは admin/challenges + setup/challenges が実参照する
	// 13 key のみ (ADR-0045 labels SSOT 整合)。sectionTitle 等の訴求文言の現モデル整合は別途 PO 判断。
	familyStreakTitle: (days: number) => `家族ストリーク: ${days}日`,
	sectionTitle: adminScreenHeading('challenges'),
	deletedNotice: 'チャレンジを削除しました',
	noChallengeTitleIcon: CONCEPT_ICONS.challenge,
	noChallengeTitle: `${CHALLENGE_TERMS.canonical}はまだありません`,
	// #4671 F8: 家族ストリークカードの日本語直書きを SSOT 化
	familyStreakRecordedToday: (count: number) => `今日は${formatPeople(count)}が記録済み`,
	familyStreakNoneToday: '今日はまだ誰も記録していません',
	badgeAllCompleted: '全員クリア！',
	/** #4689: その子だけのチャレンジ (週次自動生成は子供ごとに内容が違うためこちらが既定) */
	badgeCompleted: 'クリア！',
	badgeActive: '開催中',
	// #4716: 同じものを「報酬」「ほうしゅう」「ごほうび」の 3 語で呼んでいた。ごほうびに寄せる。
	rewardLabel: (points: number) => `${REWARD_TERMS.canonical}${points}P`,
	deleteButton: '削除',
	dateSeparator: ' 〜 ',
	periodLabelWeekly: '週間',
	periodLabelMonthly: '月間',
	periodLabelCustom: 'カスタム',
} as const;

// #2362 PR-7 (ADR-0055、User §6): per-child challenge instance + 兄弟連動 UI
export const ADMIN_CHALLENGES_PAGE_LABELS = {
	// 兄弟連動比較 UI (SiblingChallengeComparison.svelte)
	siblingComparisonHeading: 'きょうだいの進捗',
	siblingComparisonAllCompleted: 'みんな達成',
	siblingComparisonAllCompletedMessage:
		'きょうだい全員で達成しました。お子さまの努力を一緒に認めてあげましょう。',
	// 子供別タブ
	childTabAllLabel: 'すべて',
	childTabAllAriaLabel: 'すべてのお子さま',
	// per-child empty state
	// #4671 F7: 一括追加 / cross-child copy の label は #3195 の機能撤去で参照 0 件になったため削除
	perChildEmptyTitle: 'このお子さまのチャレンジはまだありません',
	// #3195: アプリ自動生成への一本化 (親手動作成撤去、読み取り専用ビュー)
	autoGeneratedDesc:
		'チャレンジはアプリが毎週自動で用意します。お子さまの記録の傾向にあわせて、苦手なことや得意なことを伸ばす目標が届きます。',
	// #4911: setup wizard (初期設定) で家族が選んだ preset / custom チャレンジのみが表示されている
	// (週次自動生成が 1 件も無い) ときは「毎週自動で用意します」と書かない (ADR-0013 実装の事実に一致)。
	// 旧実装は常に autoGeneratedDesc を出しており、setup 由来のカスタムしか無い画面で矛盾していた。
	customOnlyDesc:
		'表示されているチャレンジは、初期設定や保護者が選んで追加したものです。これとは別に、お子さまがアプリを開くと、記録の傾向にあわせた週替わりのチャレンジも自動で届きます。',
	autoGeneratedEmptyDesc: 'お子さまがアプリを開くと、今週のチャレンジが自動で用意されます。',
	// #2554 follow-up CUJ-CH2 完全化: marketplace 取込 → ChildSelectionDialog auto-open → 確定 result toast
	// (admin-rewards / admin-activities と同型 pattern、ADR-0055 per-child + family-only gate 整合)
	importSuccess: (count: number) => `✨ ${count} 件のチャレンジを追加しました`,
	importAllDuplicates: 'このチャレンジ集は既に追加済みです',
	importFailed: '取込に失敗しました',
	// #2558 bug-1 整合: デモ環境では書き込みが no-op 化される。成功偽装せず明示する。
	importDemo: 'デモではお試し用です（実際の追加は行われません）',
	importInvalidPreset: '取込対象のプリセットが見つかりませんでした',
	// #4023 横展開: 削除確認。旧実装は onsubmit + preventDefault で、キャンセルしても
	// use:enhance 側の submit listener が走り削除が通っていた (admin/settings/rules と同型)。
	deleteConfirmTitle: 'このチャレンジを削除しますか？',
	deleteConfirmBody: (challengeTitle: string, childName: string) =>
		`「${challengeTitle}」（${childName}）を削除します。削除すると、このお子さまの今の進捗も一緒に消えます。`,
	// #4512: 家族ストリークの今日の記録状況 (旧: +page.svelte の三項演算子内直書き) は
	// #4671 F8 が同一文言を CHALLENGES_LABELS.familyStreakRecordedToday / .familyStreakNoneToday
	// として先に集約済みのため、merge 時に重複定義を削除しそちらに寄せた。
	// #4512 / #4716 item 15: 兄弟 instance がある場合の削除ボタンラベル (旧: 直書きの ` を削除`)
	deleteChildButton: (childName: string) => `${childName} を削除`,
	// #4716 が「別のお子さまからコピー」の呼称共有として copyFromOtherChildAction を足していたが、
	// チャレンジの cross-child copy 導線は #4671 F7 (#3195 の自動生成一本化) で撤去済で、
	// 参照は repo 内 0 件だった。撤去済み機能のラベルを残すと「まだある」と読めるので置かない
	// (parent-wording-hygiene-4716.test.ts が not.toHaveProperty で固定している、QM #4809 レビュー)。
} as const;
