<script lang="ts">
import { enhance } from '$app/forms';
import { todayDateJST } from '$lib/domain/date-utils';
import {
	ADMIN_CHALLENGES_PAGE_LABELS,
	APP_LABELS,
	CHALLENGES_LABELS,
	PAGE_TITLES,
} from '$lib/domain/labels';
// CX-DoR #9・#11: empty state を共通 SSOT に統一 (NN/G #4 consistency)
import UnifiedEmptyState from '$lib/marketplace/ui/UnifiedEmptyState.svelte';
import type { ChildChallenge, ChildChallengeGroup } from '$lib/server/db/types';
import SiblingChallengeComparison from '$lib/ui/features/admin/SiblingChallengeComparison.svelte';
import Button from '$lib/ui/primitives/Button.svelte';

// #3195 (EPIC #3193): 親手動作成 / 競争モード / marketplace challenge-set 取込を撤去。
// チャレンジはアプリが毎週自動生成する (child-challenge-service.getOrCreateWeeklyChildChallenge)。
// 本画面は「自動生成された子のチャレンジを親が閲覧する」読み取り専用ビュー (作成 UI なし)。
// 全プランに開放 (旧 family 限定 gate を撤去)。

let { data, form } = $props();

interface RewardConfig {
	points: number;
	message?: string;
}

function parseJSON<T>(json: string, fallback: T): T {
	try {
		return JSON.parse(json);
	} catch {
		return fallback;
	}
}

function formatDate(d: string): string {
	return d.replace(/-/g, '/');
}

function isCurrentlyActive(instance: ChildChallenge): boolean {
	const today = todayDateJST();
	return (
		instance.isActive === 1 &&
		instance.status === 'active' &&
		instance.startDate <= today &&
		instance.endDate >= today
	);
}

const periodLabel = (t: string) => {
	switch (t) {
		case 'weekly':
			return CHALLENGES_LABELS.periodLabelWeekly;
		case 'monthly':
			return CHALLENGES_LABELS.periodLabelMonthly;
		default:
			return CHALLENGES_LABELS.periodLabelCustom;
	}
};

// 子供別タブ filtering
const selectedChildId = $derived(data.selectedChildId);
const filteredGroups = $derived.by((): ChildChallengeGroup[] => {
	if (selectedChildId === 'all') return data.challengeGroups;
	return data.challengeGroups
		.map((g) => ({
			...g,
			instances: g.instances.filter((i) => i.childId === selectedChildId),
		}))
		.filter((g) => g.instances.length > 0);
});

// child 別タブ URL
function tabHref(childId: number | 'all'): string {
	return childId === 'all' ? '/admin/challenges' : `/admin/challenges?childId=${childId}`;
}
</script>

<svelte:head>
	<title>{PAGE_TITLES.challenges}{APP_LABELS.pageTitleSuffix}</title>
</svelte:head>

<!-- #2905: ❓ ページガイド (CHALLENGES_GUIDE) のアンカー (最外 wrapper)。 -->
<div class="space-y-4" data-tutorial="challenges-page">
	{#if data.familyStreak && data.familyStreak.currentStreak > 0}
		<div class="rounded-xl border bg-white p-4">
			<div class="flex items-center gap-2 mb-2">
				<span class="text-xl">🔥</span>
				<h3 class="font-bold text-sm">{CHALLENGES_LABELS.familyStreakTitle(data.familyStreak.currentStreak)}</h3>
			</div>
			<p class="text-xs text-[var(--color-text-muted)]">
				{data.familyStreak.hasRecordedToday
					? `今日は${data.familyStreak.todayRecorders.length + '人'}が記録済み`
					: '今日はまだ誰も記録していません'}
			</p>
		</div>
	{/if}

	<div class="rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-info)] p-3 text-xs text-[var(--color-text-primary)]">
		<p>{ADMIN_CHALLENGES_PAGE_LABELS.autoGeneratedDesc}</p>
	</div>

	<!-- 子供別タブ -->
	{#if data.children.length > 1}
		<nav
			class="flex gap-1 overflow-x-auto"
			aria-label={ADMIN_CHALLENGES_PAGE_LABELS.childTabAllAriaLabel}
			data-testid="admin-challenges-child-tabs"
		>
			<a
				href={tabHref('all')}
				class="px-3 py-1.5 text-xs font-medium rounded-lg whitespace-nowrap {selectedChildId === 'all' ? 'bg-[var(--color-action-primary)] text-[var(--color-text-inverse)]' : 'bg-[var(--color-surface-secondary)] text-[var(--color-text-primary)]'}"
				data-testid="admin-challenges-child-tab-all"
			>
				{ADMIN_CHALLENGES_PAGE_LABELS.childTabAllLabel}
			</a>
			{#each data.children as child (child.id)}
				<a
					href={tabHref(child.id)}
					class="px-3 py-1.5 text-xs font-medium rounded-lg whitespace-nowrap {selectedChildId === child.id ? 'bg-[var(--color-action-primary)] text-[var(--color-text-inverse)]' : 'bg-[var(--color-surface-secondary)] text-[var(--color-text-primary)]'}"
					data-testid="admin-challenges-child-tab-{child.id}"
				>
					{child.nickname}
				</a>
			{/each}
		</nav>
	{/if}

	<div class="flex items-center justify-between">
		<h2 class="text-lg font-bold">{CHALLENGES_LABELS.sectionTitle}</h2>
	</div>

	{#if form?.error}
		<div class="rounded-lg bg-[var(--color-feedback-error-bg)] p-3 text-sm text-[var(--color-feedback-error-text)]">{form.error}</div>
	{/if}
	{#if form?.deleted}
		<div class="rounded-lg bg-[var(--color-surface-muted)] p-3 text-sm text-[var(--color-text-primary)]">{CHALLENGES_LABELS.deletedNotice}</div>
	{/if}

	<!-- チャレンジ group 一覧 (per-child instance + 兄弟連動表示)。読み取り専用 + 削除のみ。 -->
	{#if filteredGroups.length === 0}
		<UnifiedEmptyState
			testid="admin-challenges-empty-state"
			icon={CHALLENGES_LABELS.noChallengeTitleIcon}
			noItemsText={selectedChildId === 'all'
				? CHALLENGES_LABELS.noChallengeTitle
				: ADMIN_CHALLENGES_PAGE_LABELS.perChildEmptyTitle}
			descText={ADMIN_CHALLENGES_PAGE_LABELS.autoGeneratedEmptyDesc}
			showPrimary={false}
			canImport={false}
		/>
	{:else}
		<div class="space-y-3">
			{#each filteredGroups as group (group.groupKey)}
				{@const firstInstance = group.instances[0]}
				{@const active = firstInstance ? isCurrentlyActive(firstInstance) : false}
				{@const reward = firstInstance ? parseJSON<RewardConfig>(firstInstance.rewardConfig, { points: 0 }) : { points: 0 }}
				<div
					class="rounded-xl border bg-white p-4 space-y-3"
					class:border-[var(--color-feedback-info-border)]={active}
					data-testid="admin-challenges-group"
					data-group-key={group.groupKey}
				>
					<div class="flex items-start justify-between gap-2">
						<div class="flex-1">
							<h3 class="font-bold text-sm">
								{group.title}
								{#if group.allCompleted}
									<span class="ml-1 rounded bg-[var(--color-feedback-success-bg-strong)] px-1.5 py-0.5 text-[10px] font-bold text-[var(--color-feedback-success-text)]">{CHALLENGES_LABELS.badgeAllCompleted}</span>
								{/if}
								{#if active}
									<span class="ml-1 rounded bg-[var(--color-feedback-info-bg-strong)] px-1.5 py-0.5 text-[10px] font-bold text-[var(--color-feedback-info-text)]">{CHALLENGES_LABELS.badgeActive}</span>
								{/if}
							</h3>
							<p class="text-xs text-[var(--color-text-muted)] mt-0.5">
								{periodLabel(group.periodType)}
								· {formatDate(group.startDate)}{CHALLENGES_LABELS.dateSeparator}{formatDate(group.endDate)}
								· {CHALLENGES_LABELS.rewardLabel(reward.points)}
							</p>
							{#if group.description}
								<p class="text-xs text-[var(--color-text-secondary)] mt-1">{group.description}</p>
							{/if}
						</div>
					</div>

					<!-- 兄弟連動表示 (instance 数 ≥ 2 で展開) -->
					{#if group.instances.length >= 2}
						<SiblingChallengeComparison {group} children={data.children} />
					{:else if group.instances.length === 1 && firstInstance}
						{@const child = data.children.find((c) => c.id === firstInstance.childId)}
						{@const pct = Math.min(100, Math.round((firstInstance.currentValue / firstInstance.targetValue) * 100))}
						<div class="flex items-center gap-2" data-testid="admin-challenges-single-progress">
							<span class="text-xs font-medium text-[var(--color-text-primary)] w-20 truncate">
								{child?.nickname ?? `#${firstInstance.childId}`}
							</span>
							<div class="flex-1 h-2 bg-[var(--color-surface-secondary)] rounded-full overflow-hidden">
								<div
									class="h-full rounded-full {firstInstance.completed === 1 ? 'bg-[var(--color-feedback-success-border)]' : 'bg-[var(--color-feedback-info-border)]'}"
									style:width="{pct}%"
								></div>
							</div>
							<span class="text-[10px] text-[var(--color-text-muted)] w-14 text-right">
								{firstInstance.currentValue}/{firstInstance.targetValue}
								{#if firstInstance.completed === 1}✅{/if}
							</span>
						</div>
					{/if}

					<!-- 削除アクション (group 内 全 instance に対して 1 件ずつ) -->
					<div class="flex justify-end gap-1 flex-wrap">
						{#each group.instances as instance (instance.id)}
							{@const child = data.children.find((c) => c.id === instance.childId)}
							<form method="POST" action="?/delete" use:enhance
								onsubmit={(e) => { if (!confirm(`「${group.title}」(${child?.nickname ?? '#' + instance.childId}) を削除しますか？`)) e.preventDefault(); }}
							>
								<input type="hidden" name="id" value={instance.id} />
								<Button type="submit" variant="ghost" size="sm">
									{group.instances.length >= 2 ? `${child?.nickname ?? '#' + instance.childId} を削除` : CHALLENGES_LABELS.deleteButton}
								</Button>
							</form>
						{/each}
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>
