changelog:
  categories:
    - title: "New Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Infrastructure"
      labels:
        - "infra"
        - "github-actions"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
