# scripts/nuc/generate-env.ps1 (#4275)
#
# Generates .env for the NUC production deploy from GitHub Actions Secrets.
# Called by .github/workflows/deploy-nuc.yml (step "Generate .env from GitHub Secrets").
#
# WHY THIS IS A FILE INSTEAD OF AN INLINE `run:` BLOCK
#   The inline version broke the 2026-08-05 release: the NUC deploy failed with a
#   PowerShell parse error, so the release reached AWS but never reached the NUC
#   (#4275). Two things in the *error messages themselves* broke the script:
#     1. "--body <hex>" - PowerShell treats '<' as a reserved operator.
#     2. Japanese text - Windows PowerShell 5.1 reads script text as ANSI, so the
#        characters became mojibake and unbalanced the surrounding parentheses.
#   An inline block is only ever executed on the self-hosted NUC runner, so CI never
#   parsed it. It reached main before anyone ran it.
#
# TWO RULES FOR THIS FILE (both are machine-enforced by
# tests/unit/scripts/nuc-generate-env.test.ts):
#   - ASCII ONLY. Never put Japanese (or any non-ASCII) text here. The runner's
#     encoding is not ours to control; ASCII removes the dependency entirely.
#   - NO BARE '<' OR '>'. Use [brackets] for placeholders in messages.
#
# Exit codes: 0 = wrote .env / 1 = a required secret is missing (fail-closed).

[CmdletBinding()]
param(
    # Output path. The workflow writes to the repo root; tests write to a temp dir.
    [string]$OutFile = '.env'
)

$ErrorActionPreference = 'Stop'

$repo = 'Takenori-Kusaka/ganbari-quest'

# --- Required secrets (fail-closed) ---------------------------------------
# Missing values must stop the deploy. A deploy that "succeeds" while a required
# secret is absent is worse than a failed one: the app starts and dies later,
# where nobody is looking (#4119: 18 nights of silent backup failures).

if (-not $env:PARENT_GATE_COOKIE_SECRET) {
    Write-Host "::error::PARENT_GATE_COOKIE_SECRET is not set in GitHub Actions Secrets."
    Write-Host "::error::Generate hex with: node -e ""console.log(require('crypto').randomBytes(32).toString('hex'))"""
    Write-Host "::error::Register with: gh secret set PARENT_GATE_COOKIE_SECRET --body [hex] --repo $repo"
    Write-Host "::error::See docs/decisions/0050-parent-gate-session-cookie-signature.md and infra/CLAUDE.md."
    exit 1
}

if (-not $env:CRON_SECRET) {
    Write-Host "::error::CRON_SECRET is not set in GitHub Actions Secrets."
    Write-Host "::error::Required to authenticate /api/cron/pglite-backup. Without it the nightly backup fails every night (#4119)."
    Write-Host "::error::Register with: gh secret set CRON_SECRET --body [hex] --repo $repo"
    exit 1
}

# --- Optional secrets (warn, do not stop) ---------------------------------
# The backup itself still runs without a webhook, but its failures reach nobody.

if (-not $env:DISCORD_ALERT_WEBHOOK_URL) {
    Write-Host "::warning::DISCORD_WEBHOOK_INCIDENT is not set - backup failures will notify nobody (same state as the #4119 incident)."
}

# AI provider key (#4330). The NUC is a gemini host, so AI_PROVIDER=gemini is always
# written below. Declaring a provider without its key is what made AI suggestions
# silently dead: the provider is chosen, the key is absent, and nothing says so until
# a parent taps "suggest" and gets keyword fallback instead.
#
# WHY NOT JUST OMIT AI_PROVIDER WHEN THE KEY IS MISSING
#   Omitting it makes the factory fall back to 'bedrock', and
#   BedrockClaudeProvider.isAvailable() returns true unconditionally. On a NUC with no
#   AWS credentials the app would then claim AI works and fail at call time - strictly
#   worse than today. GeminiProvider without a key reports unavailable, so the services
#   degrade to keyword suggestions honestly. Keep gemini; warn about the key.
#
# WHY NOT FAIL THE DEPLOY
#   AI suggestions are an auxiliary feature; records, rewards and checklists work
#   without them. #4275 is the counter-example: text added to make a problem visible
#   killed the deploy itself. Warn, and let the rest of the release land.
if (-not $env:GEMINI_API_KEY) {
    Write-Host "::warning::GEMINI_API_KEY is not set - AI suggestions stay disabled on the NUC (services fall back to keyword suggestions)."
    Write-Host "::warning::Register with: gh secret set GEMINI_API_KEY --body [key] --repo $repo (get a key at https://aistudio.google.com/)."
}

# --- Write .env -----------------------------------------------------------
# Regenerated from GitHub Actions Secrets on every deploy (rotation-safe, idempotent).
# ASCII encoding avoids a BOM, which docker compose env_file rejects.
# Anything not listed here disappears from .env on the next deploy: this list is the
# whole contract (#4167).

$envLines = @(
    "# Auto-generated by scripts/nuc/generate-env.ps1 from GitHub Actions Secrets.",
    "# DO NOT EDIT MANUALLY. Rotate via: gh secret set [NAME] --body [value] --repo $repo",
    "PARENT_GATE_COOKIE_SECRET=$env:PARENT_GATE_COOKIE_SECRET",
    # The NUC has no AWS credentials, so bedrock (the factory default) must never be
    # selected here. Its key is written below, only when present (#4330).
    "AI_PROVIDER=gemini",
    "ORIGIN=http://0.0.0.0:3000",
    "DATA_SOURCE=pglite",
    "PGLITE_DATA_DIR=/app/data/pglite",
    "CRON_SECRET=$env:CRON_SECRET"
)

# Optional env vars are written only when set. Writing an empty value would make
# "set but empty" indistinguishable from "not set".
if ($env:DISCORD_ALERT_WEBHOOK_URL) {
    $envLines += "DISCORD_ALERT_WEBHOOK_URL=$env:DISCORD_ALERT_WEBHOOK_URL"
}
if ($env:HOST_BACKUP_DIR) {
    $envLines += "HOST_BACKUP_DIR=$env:HOST_BACKUP_DIR"
}
# Pairs with AI_PROVIDER=gemini above (#4330). Without this line the provider is
# declared but has no key, and AI suggestions are dead with nothing reporting it.
if ($env:GEMINI_API_KEY) {
    $envLines += "GEMINI_API_KEY=$env:GEMINI_API_KEY"
}

Set-Content -Path $OutFile -Value $envLines -Encoding ASCII
Write-Host "Wrote $OutFile from GitHub Secrets ($($envLines.Count) lines, secret values masked)"
