// scripts/generate-version.ts
// 日付ベースバージョンを自動生成して src/lib/version.ts に書き出す
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { todayDateJST } from '../src/lib/domain/date-utils';

const VERSION_FILE = 'src/lib/version.ts';
const MAJOR = process.env.APP_MAJOR_VERSION || '1';

function generateVersion(): string {
	// 版数の日付部は JST 暦日 (暦 SSOT 経由、#4120)
	const dateStr = todayDateJST().replace(/-/g, '');

	let patch = 0;

	// 既存のバージョンファイルがあれば、同日のpatchをインクリメント
	if (existsSync(VERSION_FILE)) {
		const content = readFileSync(VERSION_FILE, 'utf-8');
		const match = content.match(/v(\d+)\.(\d{8})\.(\d+)/);
		if (match) {
			const existingDate = match[2];
			const existingPatch = match[3];
			if (existingDate === dateStr) {
				patch = Number.parseInt(existingPatch, 10) + 1;
			}
		}
	}

	return `v${MAJOR}.${dateStr}.${patch}`;
}

const version = generateVersion();
const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually

export const APP_VERSION = '${version}' as const;
export const APP_VERSION_DATE = '${new Date().toISOString()}' as const;
`;

writeFileSync(VERSION_FILE, content);
console.log(`Generated version: ${version}`);
