/**
 * Demo Mode — Static preset data for demo experience
 * All data is read-only. Write operations return success without persisting.
 *
 * Family: がんばり家
 * #703: 5年齢パターン × 男女ミックスの 5 人構成。年齢別プリセット活動を確認でき、
 *       かつ男女のバリエーションも表現する。
 *
 * - Parent: がんばり太郎
 * - Child 1 (901): たろう (1歳, baby M, blue)        — Level 2
 * - Child 2 (902): はなこ (5歳, preschool F, pink)   — Level 4
 * - Child 3 (903): けんた (8歳, elementary M, green) — Level 7
 * - Child 4 (904): さくら (14歳, junior F, purple)   — Level 15+
 * - Child 5 (906): ゆうき (17歳, senior M, orange)   — Level 20+
 */

import { getDefaultUiMode } from '$lib/domain/validation/age-tier';
import type {
	Activity,
	ActivityLog,
	ChecklistTemplate,
	ChecklistTemplateItem,
	Child,
	ChildAchievement,
	DailyMission,
	LoginBonus,
	Status,
} from '$lib/server/db/types/index.js';

// ============================================================
// Constants
// ============================================================

const DEMO_TENANT_ID = 'demo';
const NOW = '2026-03-27T09:00:00.000Z';
const TODAY = '2026-03-27';

function daysAgo(n: number): string {
	const d = new Date('2026-03-27');
	d.setDate(d.getDate() - n);
	return d.toISOString().slice(0, 10);
}

function daysAgoISO(n: number): string {
	const d = new Date('2026-03-27T09:00:00.000Z');
	d.setDate(d.getDate() - n);
	return d.toISOString();
}

// ============================================================
// Children
// ============================================================

export const DEMO_CHILDREN: Child[] = [
	// 901 — 乳幼児 (男): blue テーマ
	{
		id: 901,
		nickname: 'たろう',
		age: 1,
		birthDate: '2025-01-15',
		theme: 'blue',
		uiMode: getDefaultUiMode(1),
		avatarUrl: null,
		displayConfig: null,
		userId: null,
		birthdayBonusMultiplier: 1.0,
		lastBirthdayBonusYear: null,
		isArchived: 0,
		archivedReason: null,
		createdAt: '2026-01-01T00:00:00.000Z',
		updatedAt: NOW,
	},
	// 902 — 幼児 (女): pink テーマ
	{
		id: 902,
		nickname: 'はなこ',
		age: 5,
		birthDate: '2020-06-10',
		theme: 'pink',
		uiMode: getDefaultUiMode(5),
		avatarUrl: null,
		displayConfig: null,
		userId: null,
		birthdayBonusMultiplier: 1.0,
		lastBirthdayBonusYear: null,
		isArchived: 0,
		archivedReason: null,
		createdAt: '2025-09-01T00:00:00.000Z',
		updatedAt: NOW,
	},
	// 903 — 小学生 (男): green テーマ
	{
		id: 903,
		nickname: 'けんた',
		age: 8,
		birthDate: '2018-03-22',
		theme: 'green',
		uiMode: getDefaultUiMode(8),
		avatarUrl: null,
		displayConfig: null,
		userId: null,
		birthdayBonusMultiplier: 1.0,
		lastBirthdayBonusYear: null,
		isArchived: 0,
		archivedReason: null,
		createdAt: '2025-04-01T00:00:00.000Z',
		updatedAt: NOW,
	},
	// 904 — 中学生 (女): purple テーマ
	{
		id: 904,
		nickname: 'さくら',
		age: 14,
		birthDate: '2011-08-05',
		theme: 'purple',
		uiMode: getDefaultUiMode(14),
		avatarUrl: null,
		displayConfig: null,
		userId: null,
		birthdayBonusMultiplier: 1.0,
		lastBirthdayBonusYear: null,
		isArchived: 0,
		archivedReason: null,
		createdAt: '2025-04-01T00:00:00.000Z',
		updatedAt: NOW,
	},
	// 906 — 高校生 (男): orange テーマ
	{
		id: 906,
		nickname: 'ゆうき',
		age: 17,
		birthDate: '2008-11-20',
		theme: 'orange',
		uiMode: getDefaultUiMode(17),
		avatarUrl: null,
		displayConfig: null,
		userId: null,
		birthdayBonusMultiplier: 1.0,
		lastBirthdayBonusYear: null,
		isArchived: 0,
		archivedReason: null,
		createdAt: '2025-04-01T00:00:00.000Z',
		updatedAt: NOW,
	},
];

// ============================================================
// Activities (shared across all children)
// ============================================================

export const DEMO_ACTIVITIES: Activity[] = [
	// ============================================================
	// アクティビティパック準拠の活動データ
	// baby-first / kinder-starter / elementary-challenge パック + 上位年齢用
	// ============================================================

	// 運動 (categoryId: 1)
	{
		id: 1,
		name: 'はいはいした',
		categoryId: 1,
		icon: '🐣',
		basePoints: 3,
		ageMin: 0,
		ageMax: 1,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 1,
		source: 'pack',
		gradeLevel: 'baby',
		subcategory: null,
		description: '這う・伝い歩きなど基本運動',
		nameKana: 'はいはいした',
		nameKanji: null,
		triggerHint: 'マットで はいはい してみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 2,
		name: 'あんよした',
		categoryId: 1,
		icon: '👣',
		basePoints: 5,
		ageMin: 0,
		ageMax: 2,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 2,
		source: 'pack',
		gradeLevel: 'baby',
		subcategory: null,
		description: '歩行の練習・伝い歩き',
		nameKana: 'あんよした',
		nameKanji: null,
		triggerHint: 'てを つないで あるいてみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 3,
		name: 'おそとにでた',
		categoryId: 1,
		icon: '🌿',
		basePoints: 3,
		ageMin: 0,
		ageMax: 2,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 3,
		source: 'pack',
		gradeLevel: 'baby',
		subcategory: null,
		description: '戸外で外気に触れ体を動かす',
		nameKana: 'おそとにでた',
		nameKanji: null,
		triggerHint: 'おそとの かぜを かんじよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 4,
		name: 'からだをうごかした',
		categoryId: 1,
		icon: '🤸',
		basePoints: 5,
		ageMin: 0,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 4,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '外遊び・体操・かけっこ',
		nameKana: 'からだをうごかした',
		nameKanji: null,
		triggerHint: 'おそとで いっぱい あそぼう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 5,
		name: 'なわとびした',
		categoryId: 1,
		icon: '🪢',
		basePoints: 5,
		ageMin: 4,
		ageMax: 9,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 5,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '縄跳びの練習',
		nameKana: 'なわとびした',
		nameKanji: null,
		triggerHint: 'なわとび れんしゅう してみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 6,
		name: 'ダンスした',
		categoryId: 1,
		icon: '💃',
		basePoints: 5,
		ageMin: 3,
		ageMax: 9,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 6,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '音楽に合わせたダンス',
		nameKana: 'だんすした',
		nameKanji: null,
		triggerHint: 'おんがくに あわせて おどろう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 7,
		name: 'うんどうした',
		categoryId: 1,
		icon: '🏃',
		basePoints: 10,
		ageMin: 6,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 7,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: 'スポーツ・運動全般',
		nameKana: 'うんどうした',
		nameKanji: '運動した',
		triggerHint: 'からだを うごかそう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// 勉強 (categoryId: 2)
	{
		id: 10,
		name: 'えほんをよんだ',
		categoryId: 2,
		icon: '📖',
		basePoints: 5,
		ageMin: 0,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 1,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '絵本を読む・読み聞かせ',
		nameKana: 'えほんをよんだ',
		nameKanji: null,
		triggerHint: 'えほんを よんでみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 11,
		name: 'すうじをかぞえた',
		categoryId: 2,
		icon: '🔢',
		basePoints: 5,
		ageMin: 3,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 2,
		source: 'pack',
		gradeLevel: 'kinder',
		subcategory: null,
		description: '1〜10の数を数える',
		nameKana: 'すうじをかぞえた',
		nameKanji: null,
		triggerHint: 'いち、に、さん… かぞえよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 12,
		name: 'ひらがなれんしゅう',
		categoryId: 2,
		icon: '✏️',
		basePoints: 10,
		ageMin: 4,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 3,
		source: 'pack',
		gradeLevel: 'kinder',
		subcategory: null,
		description: 'ひらがなの読み書き練習',
		nameKana: 'ひらがなれんしゅう',
		nameKanji: null,
		triggerHint: 'ひらがなを かいてみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 13,
		name: 'しゅくだいをした',
		categoryId: 2,
		icon: '📝',
		basePoints: 10,
		ageMin: 6,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 4,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '学校の宿題を完了',
		nameKana: 'しゅくだいをした',
		nameKanji: '宿題をした',
		triggerHint: 'きょうの しゅくだい おわらせよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 14,
		name: 'どくしょした',
		categoryId: 2,
		icon: '📚',
		basePoints: 10,
		ageMin: 6,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 5,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '本・図書を読む',
		nameKana: 'どくしょした',
		nameKanji: '読書した',
		triggerHint: 'ほんを よもう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 15,
		name: 'けいさんれんしゅう',
		categoryId: 2,
		icon: '🔢',
		basePoints: 10,
		ageMin: 6,
		ageMax: 9,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 6,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '計算ドリル・算数プリント',
		nameKana: 'けいさんれんしゅう',
		nameKanji: '計算練習',
		triggerHint: 'けいさんドリルを やろう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// --- upper (9-12) / teen (13+) 向け追加 ---
	{
		id: 16,
		name: '自主学習した',
		categoryId: 2,
		icon: '📓',
		basePoints: 15,
		ageMin: 9,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 7,
		source: 'pack',
		gradeLevel: 'elementary_upper',
		subcategory: null,
		description: '教科書・参考書を使った自主学習',
		nameKana: 'じしゅがくしゅうした',
		nameKanji: '自主学習した',
		triggerHint: 'じぶんで べんきょうを すすめよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 17,
		name: '受験勉強した',
		categoryId: 2,
		icon: '🎓',
		basePoints: 20,
		ageMin: 13,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 8,
		source: 'pack',
		gradeLevel: 'middle_school',
		subcategory: null,
		description: '受験に向けた勉強・過去問演習',
		nameKana: 'じゅけんべんきょうした',
		nameKanji: '受験勉強した',
		triggerHint: '目標に向かって勉強しよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 18,
		name: '資格・検定の勉強',
		categoryId: 2,
		icon: '📜',
		basePoints: 20,
		ageMin: 13,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 9,
		source: 'pack',
		gradeLevel: 'middle_school',
		subcategory: null,
		description: '英検・漢検・数検などの資格勉強',
		nameKana: 'しかく・けんていのべんきょう',
		nameKanji: '資格・検定の勉強',
		triggerHint: '資格取得に向けて勉強しよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// 運動 — upper/teen 追加
	{
		id: 8,
		name: '部活・習い事',
		categoryId: 1,
		icon: '⚽',
		basePoints: 15,
		ageMin: 9,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 8,
		source: 'pack',
		gradeLevel: 'elementary_upper',
		subcategory: null,
		description: '部活動やスポーツ系習い事',
		nameKana: 'ぶかつ・ならいごと',
		nameKanji: '部活・習い事',
		triggerHint: 'きょうの部活・習い事がんばろう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// 生活 (categoryId: 3)
	{
		id: 20,
		name: 'はみがきした',
		categoryId: 3,
		icon: '🪥',
		basePoints: 5,
		ageMin: 0,
		ageMax: null,
		isVisible: 1,
		dailyLimit: 0,
		sortOrder: 1,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '食後の歯磨き',
		nameKana: 'はみがきした',
		nameKanji: null,
		triggerHint: 'ごはんのあと はみがきしよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 21,
		name: 'おきがえした',
		categoryId: 3,
		icon: '👕',
		basePoints: 5,
		ageMin: 0,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 2,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '自分で着替え',
		nameKana: 'おきがえした',
		nameKanji: null,
		triggerHint: 'じぶんで おきがえ してみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 22,
		name: 'おかたづけした',
		categoryId: 3,
		icon: '🧹',
		basePoints: 5,
		ageMin: 3,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 3,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: 'おもちゃ・部屋の片付け',
		nameKana: 'おかたづけした',
		nameKanji: '片付けした',
		triggerHint: 'あそんだあと おかたづけ！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 23,
		name: 'てをあらった',
		categoryId: 3,
		icon: '🧼',
		basePoints: 3,
		ageMin: 0,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 4,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '帰宅時・食前の手洗い',
		nameKana: 'てをあらった',
		nameKanji: null,
		triggerHint: 'おそとから かえったら てあらい！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 24,
		name: 'はやおきした',
		categoryId: 3,
		icon: '⏰',
		basePoints: 5,
		ageMin: 3,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 5,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '決まった時間に起床',
		nameKana: 'はやおきした',
		nameKanji: '早起きした',
		triggerHint: 'あさ じかんどおりに おきよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 25,
		name: 'おてつだいした',
		categoryId: 3,
		icon: '🫧',
		basePoints: 10,
		ageMin: 3,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 6,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '食事の準備・配膳のお手伝い等',
		nameKana: 'おてつだいした',
		nameKanji: 'お手伝いした',
		triggerHint: 'おうちの おてつだい してみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 26,
		name: 'ごはんをたべた',
		categoryId: 3,
		icon: '🍚',
		basePoints: 3,
		ageMin: 0,
		ageMax: 2,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 7,
		source: 'pack',
		gradeLevel: 'baby',
		subcategory: null,
		description: '離乳食・幼児食を食べる',
		nameKana: 'ごはんをたべた',
		nameKanji: null,
		triggerHint: 'もぐもぐ ごはんを たべよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 27,
		name: 'じかんわりのじゅんび',
		categoryId: 3,
		icon: '🎒',
		basePoints: 5,
		ageMin: 6,
		ageMax: 9,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 8,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '翌日の持ち物・教科書の準備',
		nameKana: 'じかんわりのじゅんび',
		nameKanji: '時間割の準備',
		triggerHint: 'あしたの じゅんび しておこう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// --- 生活: upper/teen 追加 ---
	{
		id: 28,
		name: '家事手伝い',
		categoryId: 3,
		icon: '🍳',
		basePoints: 10,
		ageMin: 9,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 9,
		source: 'pack',
		gradeLevel: 'elementary_upper',
		subcategory: null,
		description: '料理・洗濯・掃除など家事全般',
		nameKana: 'かじてつだい',
		nameKanji: '家事手伝い',
		triggerHint: 'おうちの家事を手伝おう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// 交流 (categoryId: 4)
	{
		id: 30,
		name: 'あいさつした',
		categoryId: 4,
		icon: '👋',
		basePoints: 3,
		ageMin: 0,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 1,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '元気な挨拶・お礼',
		nameKana: 'あいさつした',
		nameKanji: '挨拶した',
		triggerHint: 'おはよう、ありがとう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 31,
		name: 'いっしょにあそんだ',
		categoryId: 4,
		icon: '🤝',
		basePoints: 5,
		ageMin: 3,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 2,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: 'お友達との協力遊び',
		nameKana: 'いっしょにあそんだ',
		nameKanji: '一緒に遊んだ',
		triggerHint: 'おともだちと あそぼう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 32,
		name: 'ありがとうをいった',
		categoryId: 4,
		icon: '💕',
		basePoints: 3,
		ageMin: 3,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 3,
		source: 'pack',
		gradeLevel: 'kinder',
		subcategory: null,
		description: '感謝の気持ちを伝える',
		nameKana: 'ありがとうをいった',
		nameKanji: null,
		triggerHint: 'ありがとう って いえるかな？',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 33,
		name: 'じゅんばんをまもった',
		categoryId: 4,
		icon: '🙋',
		basePoints: 5,
		ageMin: 3,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 4,
		source: 'pack',
		gradeLevel: 'kinder',
		subcategory: null,
		description: '順番を守る・交代する',
		nameKana: 'じゅんばんをまもった',
		nameKanji: null,
		triggerHint: 'じゅんばんこ できるかな？',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 34,
		name: 'にこにこした',
		categoryId: 4,
		icon: '😊',
		basePoints: 3,
		ageMin: 0,
		ageMax: 2,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 5,
		source: 'pack',
		gradeLevel: 'baby',
		subcategory: null,
		description: '笑顔のコミュニケーション',
		nameKana: 'にこにこした',
		nameKanji: null,
		triggerHint: 'にこにこ えがおを みせよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// --- 交流: teen 追加 ---
	{
		id: 35,
		name: 'ボランティア活動',
		categoryId: 4,
		icon: '🤲',
		basePoints: 20,
		ageMin: 13,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 6,
		source: 'pack',
		gradeLevel: 'middle_school',
		subcategory: null,
		description: '地域活動・ボランティアへの参加',
		nameKana: 'ぼらんてぃあかつどう',
		nameKanji: 'ボランティア活動',
		triggerHint: '地域のために活動しよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// 創造 (categoryId: 5)
	{
		id: 40,
		name: 'おえかきした',
		categoryId: 5,
		icon: '🖍️',
		basePoints: 5,
		ageMin: 0,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 1,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '自由にお絵描き',
		nameKana: 'おえかきした',
		nameKanji: null,
		triggerHint: 'すきなものを かいてみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 41,
		name: 'こうさくした',
		categoryId: 5,
		icon: '✂️',
		basePoints: 10,
		ageMin: 3,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 2,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '折り紙・切り貼り・工作',
		nameKana: 'こうさくした',
		nameKanji: '工作した',
		triggerHint: 'はさみや のりで つくろう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 42,
		name: 'おうたをうたった',
		categoryId: 5,
		icon: '🎵',
		basePoints: 5,
		ageMin: 0,
		ageMax: 5,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 3,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: '童謡やリズム遊び',
		nameKana: 'おうたをうたった',
		nameKanji: null,
		triggerHint: 'おうたを うたおう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 43,
		name: 'ピアノれんしゅう',
		categoryId: 5,
		icon: '🎹',
		basePoints: 15,
		ageMin: 5,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 4,
		source: 'pack',
		gradeLevel: null,
		subcategory: null,
		description: 'ピアノ・楽器の練習',
		nameKana: 'ぴあのれんしゅう',
		nameKanji: 'ピアノ練習',
		triggerHint: 'すきな きょくを ひいてみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},

	// ============================================================
	// senior 専用 (age 16+) — #1147 中高生差別化
	// ============================================================
	{
		id: 50,
		name: '大学受験勉強した',
		categoryId: 2,
		icon: '🎯',
		basePoints: 25,
		ageMin: 16,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 10,
		source: 'pack',
		gradeLevel: 'high_school',
		subcategory: null,
		description: '大学受験・共通テスト対策',
		nameKana: 'だいがくじゅけんべんきょうした',
		nameKanji: '大学受験勉強した',
		triggerHint: '志望校合格に向けて勉強しよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 51,
		name: 'アルバイトした',
		categoryId: 3,
		icon: '💼',
		basePoints: 20,
		ageMin: 16,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 10,
		source: 'pack',
		gradeLevel: 'high_school',
		subcategory: null,
		description: 'アルバイト・社会経験',
		nameKana: 'あるばいとした',
		nameKanji: 'アルバイトした',
		triggerHint: '社会経験を積もう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 52,
		name: '自動車学校',
		categoryId: 2,
		icon: '🚗',
		basePoints: 15,
		ageMin: 17,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 11,
		source: 'pack',
		gradeLevel: 'high_school',
		subcategory: null,
		description: '自動車学校・教習所',
		nameKana: 'じどうしゃがっこう',
		nameKanji: '自動車学校',
		triggerHint: '運転免許取得に向けて頑張ろう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
	{
		id: 53,
		name: '進路相談',
		categoryId: 4,
		icon: '🎓',
		basePoints: 15,
		ageMin: 16,
		ageMax: null,
		isVisible: 1,
		dailyLimit: null,
		sortOrder: 7,
		source: 'pack',
		gradeLevel: 'high_school',
		subcategory: null,
		description: '進路について先生・家族と相談',
		nameKana: 'しんろそうだん',
		nameKanji: '進路相談',
		triggerHint: '将来について話してみよう！',
		isMainQuest: 0,
		isArchived: 0,
		archivedReason: null,
		createdAt: NOW,
	},
];

// ============================================================
// Activity Logs (recent 14 days for each child)
// ============================================================

// Use fixed seed approach for deterministic data
export const DEMO_ACTIVITY_LOGS: ActivityLog[] = [
	// 901 たろう (baby, age 1) — simple logs
	...[0, 1, 2, 3, 5, 7, 10].flatMap((d, i) => [
		{
			id: 901001 + i * 2,
			childId: 901,
			activityId: 1,
			points: 11,
			streakDays: 3,
			streakBonus: 2,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 901002 + i * 2,
			childId: 901,
			activityId: 20,
			points: 6,
			streakDays: 3,
			streakBonus: 1,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
	]),
	// 902 はなこ (preschool, age 5) — moderate activity
	...[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13].flatMap((d, i) => [
		{
			id: 902001 + i * 3,
			childId: 902,
			activityId: 4, // からだをうごかした (age 0-5)
			points: 7,
			streakDays: 10,
			streakBonus: 2,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 902002 + i * 3,
			childId: 902,
			activityId: 10, // えほんをよんだ (age 0-5)
			points: 7,
			streakDays: 10,
			streakBonus: 2,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		...(d % 2 === 0
			? [
					{
						id: 902003 + i * 3,
						childId: 902,
						activityId: 25, // おてつだいした (age 3+)
						points: 12,
						streakDays: 5,
						streakBonus: 2,
						recordedDate: daysAgo(d),
						recordedAt: daysAgoISO(d),
						cancelled: 0,
					},
				]
			: []),
	]),
	// 903 けんた (elementary, age 8) — active with variety
	...[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].flatMap((d, i) => [
		{
			id: 903001 + i * 4,
			childId: 903,
			activityId: 13, // しゅくだいをした (age 6+)
			points: 18,
			streakDays: 14,
			streakBonus: 7,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 903002 + i * 4,
			childId: 903,
			activityId: 7, // うんどうした (age 6+)
			points: 13,
			streakDays: 14,
			streakBonus: 7,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 903003 + i * 4,
			childId: 903,
			activityId: 22,
			points: 17,
			streakDays: 14,
			streakBonus: 5,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		...(d % 3 === 0
			? [
					{
						id: 903004 + i * 4,
						childId: 903,
						activityId: 40,
						points: 18,
						streakDays: 5,
						streakBonus: 3,
						recordedDate: daysAgo(d),
						recordedAt: daysAgoISO(d),
						cancelled: 0,
					},
				]
			: []),
	]),
	// 904 さくら (junior, age 14) — very active, all categories
	...[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].flatMap((d, i) => [
		{
			id: 904001 + i * 5,
			childId: 904,
			activityId: 7, // うんどうした (age 6+)
			points: 15,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 904002 + i * 5,
			childId: 904,
			activityId: 13, // しゅくだいをした (age 6+)
			points: 15,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 904003 + i * 5,
			childId: 904,
			activityId: 17, // 受験勉強した (age 13+)
			points: 25,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 904004 + i * 5,
			childId: 904,
			activityId: 18, // 資格・検定の勉強 (age 13+)
			points: 20,
			streakDays: 14,
			streakBonus: 8,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 904005 + i * 5,
			childId: 904,
			activityId: 43, // ピアノれんしゅう
			points: 30,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
	]),
	// 906 ゆうき (senior, age 17) — very active, senior 専用活動中心
	...[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].flatMap((d, i) => [
		{
			id: 906001 + i * 5,
			childId: 906,
			activityId: 50, // 大学受験勉強した (senior 専用)
			points: 35,
			streakDays: 14,
			streakBonus: 12,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 906002 + i * 5,
			childId: 906,
			activityId: 51, // アルバイトした (senior 専用)
			points: 28,
			streakDays: 10,
			streakBonus: 8,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 906003 + i * 5,
			childId: 906,
			activityId: 18, // 資格・検定の勉強
			points: 25,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 906004 + i * 5,
			childId: 906,
			activityId: 52, // 自動車学校 (senior 専用)
			points: 20,
			streakDays: 7,
			streakBonus: 5,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
		{
			id: 906005 + i * 5,
			childId: 906,
			activityId: 7, // 運動した
			points: 20,
			streakDays: 14,
			streakBonus: 10,
			recordedDate: daysAgo(d),
			recordedAt: daysAgoISO(d),
			cancelled: 0,
		},
	]),
];

// ============================================================
// Status (5-axis per child)
// ============================================================

export const DEMO_STATUSES: Status[] = [
	// 901 たろう (baby, Lv.2) — 15 XP 程度
	{ id: 9011, childId: 901, categoryId: 1, totalXp: 20, level: 2, peakXp: 20, updatedAt: NOW },
	{ id: 9012, childId: 901, categoryId: 2, totalXp: 10, level: 1, peakXp: 10, updatedAt: NOW },
	{ id: 9013, childId: 901, categoryId: 3, totalXp: 25, level: 2, peakXp: 25, updatedAt: NOW },
	{ id: 9014, childId: 901, categoryId: 4, totalXp: 12, level: 1, peakXp: 12, updatedAt: NOW },
	{ id: 9015, childId: 901, categoryId: 5, totalXp: 18, level: 2, peakXp: 18, updatedAt: NOW },
	// 902 はなこ (preschool, Lv.4) — 80-140 XP
	{ id: 9021, childId: 902, categoryId: 1, totalXp: 120, level: 4, peakXp: 120, updatedAt: NOW },
	{ id: 9022, childId: 902, categoryId: 2, totalXp: 90, level: 4, peakXp: 90, updatedAt: NOW },
	{ id: 9023, childId: 902, categoryId: 3, totalXp: 75, level: 3, peakXp: 75, updatedAt: NOW },
	{ id: 9024, childId: 902, categoryId: 4, totalXp: 55, level: 3, peakXp: 55, updatedAt: NOW },
	{ id: 9025, childId: 902, categoryId: 5, totalXp: 100, level: 4, peakXp: 100, updatedAt: NOW },
	// 903 けんた (elementary, Lv.7) — 275-500 XP
	{ id: 9031, childId: 903, categoryId: 1, totalXp: 450, level: 9, peakXp: 450, updatedAt: NOW },
	{ id: 9032, childId: 903, categoryId: 2, totalXp: 350, level: 8, peakXp: 350, updatedAt: NOW },
	{ id: 9033, childId: 903, categoryId: 3, totalXp: 300, level: 7, peakXp: 300, updatedAt: NOW },
	{ id: 9034, childId: 903, categoryId: 4, totalXp: 200, level: 6, peakXp: 200, updatedAt: NOW },
	{ id: 9035, childId: 903, categoryId: 5, totalXp: 280, level: 7, peakXp: 280, updatedAt: NOW },
	// 904 さくら (junior, Lv.15+) — 1200-2500 XP
	{ id: 9041, childId: 904, categoryId: 1, totalXp: 2000, level: 18, peakXp: 2000, updatedAt: NOW },
	{ id: 9042, childId: 904, categoryId: 2, totalXp: 2500, level: 20, peakXp: 2500, updatedAt: NOW },
	{ id: 9043, childId: 904, categoryId: 3, totalXp: 1200, level: 15, peakXp: 1200, updatedAt: NOW },
	{ id: 9044, childId: 904, categoryId: 4, totalXp: 800, level: 10, peakXp: 800, updatedAt: NOW },
	{ id: 9045, childId: 904, categoryId: 5, totalXp: 1800, level: 17, peakXp: 1800, updatedAt: NOW },
	// 906 ゆうき (senior, Lv.20+) — 2000-3000 XP
	{ id: 9061, childId: 906, categoryId: 1, totalXp: 2800, level: 22, peakXp: 2800, updatedAt: NOW },
	{ id: 9062, childId: 906, categoryId: 2, totalXp: 3000, level: 23, peakXp: 3000, updatedAt: NOW },
	{ id: 9063, childId: 906, categoryId: 3, totalXp: 2200, level: 19, peakXp: 2200, updatedAt: NOW },
	{ id: 9064, childId: 906, categoryId: 4, totalXp: 2000, level: 18, peakXp: 2000, updatedAt: NOW },
	{ id: 9065, childId: 906, categoryId: 5, totalXp: 2500, level: 20, peakXp: 2500, updatedAt: NOW },
];

// ============================================================
// Point Balances (computed from logs)
// ============================================================

export const DEMO_POINT_BALANCES: Record<number, number> = {
	901: 180, // たろう (baby) — low
	902: 1250, // はなこ (preschool) — moderate
	903: 3400, // けんた (elementary) — active
	904: 8500, // さくら (junior) — very active
	906: 12000, // ゆうき (senior) — most active
};

// ============================================================
// Achievements
// ============================================================

export const DEMO_CHILD_ACHIEVEMENTS: ChildAchievement[] = [
	// 902 はなこ (preschool)
	{ id: 1, childId: 902, achievementId: 1, milestoneValue: null, unlockedAt: daysAgoISO(20) },
	{ id: 2, childId: 902, achievementId: 2, milestoneValue: 10, unlockedAt: daysAgoISO(15) },
	// 903 けんた (elementary)
	{ id: 3, childId: 903, achievementId: 1, milestoneValue: null, unlockedAt: daysAgoISO(60) },
	{ id: 4, childId: 903, achievementId: 2, milestoneValue: 10, unlockedAt: daysAgoISO(50) },
	{ id: 5, childId: 903, achievementId: 2, milestoneValue: 50, unlockedAt: daysAgoISO(30) },
	{ id: 6, childId: 903, achievementId: 3, milestoneValue: null, unlockedAt: daysAgoISO(25) },
	{ id: 7, childId: 903, achievementId: 4, milestoneValue: null, unlockedAt: daysAgoISO(10) },
	// 904 さくら (junior)
	{ id: 8, childId: 904, achievementId: 1, milestoneValue: null, unlockedAt: daysAgoISO(90) },
	{ id: 9, childId: 904, achievementId: 2, milestoneValue: 10, unlockedAt: daysAgoISO(80) },
	{ id: 10, childId: 904, achievementId: 2, milestoneValue: 50, unlockedAt: daysAgoISO(60) },
	{ id: 11, childId: 904, achievementId: 2, milestoneValue: 100, unlockedAt: daysAgoISO(30) },
	{ id: 12, childId: 904, achievementId: 3, milestoneValue: null, unlockedAt: daysAgoISO(70) },
	{ id: 13, childId: 904, achievementId: 4, milestoneValue: null, unlockedAt: daysAgoISO(50) },
	{ id: 14, childId: 904, achievementId: 5, milestoneValue: null, unlockedAt: daysAgoISO(20) },
];

// ============================================================
// Daily Missions (today)
// ============================================================

export const DEMO_DAILY_MISSIONS: DailyMission[] = [
	// 902 はなこ (preschool, age 5) — 3 missions, 1 done
	{ id: 1, childId: 902, missionDate: TODAY, activityId: 4, completed: 1, completedAt: NOW }, // からだをうごかした
	{ id: 2, childId: 902, missionDate: TODAY, activityId: 10, completed: 0, completedAt: null }, // えほんをよんだ
	{ id: 3, childId: 902, missionDate: TODAY, activityId: 30, completed: 0, completedAt: null }, // あいさつした
	// 903 けんた (elementary, age 8) — 3 missions, 2 done
	{ id: 4, childId: 903, missionDate: TODAY, activityId: 13, completed: 1, completedAt: NOW }, // しゅくだいをした
	{ id: 5, childId: 903, missionDate: TODAY, activityId: 7, completed: 1, completedAt: NOW }, // うんどうした
	{ id: 6, childId: 903, missionDate: TODAY, activityId: 40, completed: 0, completedAt: null }, // おえかきした
	// 904 さくら (junior, age 14) — 3 missions, all done
	{ id: 7, childId: 904, missionDate: TODAY, activityId: 7, completed: 1, completedAt: NOW }, // うんどうした
	{ id: 8, childId: 904, missionDate: TODAY, activityId: 17, completed: 1, completedAt: NOW }, // 受験勉強した
	{ id: 9, childId: 904, missionDate: TODAY, activityId: 43, completed: 1, completedAt: NOW }, // ピアノれんしゅう
	// 906 ゆうき (senior, age 17) — 3 missions, 2 done (senior 専用: 大学受験 + アルバイト)
	{ id: 13, childId: 906, missionDate: TODAY, activityId: 50, completed: 1, completedAt: NOW }, // 大学受験勉強した
	{ id: 14, childId: 906, missionDate: TODAY, activityId: 51, completed: 1, completedAt: NOW }, // アルバイトした
	{ id: 15, childId: 906, missionDate: TODAY, activityId: 52, completed: 0, completedAt: null }, // 自動車学校
];

// ============================================================
// Checklist Templates
// ============================================================

export const DEMO_CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
	// #703: 5 年齢パターン分のチェックリスト
	// baby (901 たろう) → おでかけのじゅんび
	// preschool (902 はなこ) → あさのしたく
	// elementary (903 けんた) → よるのじゅんび
	// junior (904 さくら) → 中学生の登校準備
	// senior (906 ゆうき) → 高校生の登校準備
	{
		id: 900,
		childId: 901,
		name: 'おでかけのじゅんび',
		icon: '🍼',
		pointsPerItem: 2,
		completionBonus: 5,
		timeSlot: 'morning',
		isActive: 1,
		isArchived: 0,
		archivedReason: null,
		// #1168: 持ち物系（おむつ・きがえ・ぼうし 等のパッキング）
		kind: 'item',
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: 901,
		childId: 902,
		name: 'あさのしたく',
		icon: '☀️',
		pointsPerItem: 2,
		completionBonus: 5,
		timeSlot: 'morning',
		isActive: 1,
		isArchived: 0,
		archivedReason: null,
		// #1168: ルーティン（はみがき・きがえ・あさごはん 等の行動）
		kind: 'routine',
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: 902,
		childId: 903,
		name: 'よるのじゅんび',
		icon: '🌙',
		pointsPerItem: 2,
		completionBonus: 5,
		timeSlot: 'evening',
		isActive: 1,
		isArchived: 0,
		archivedReason: null,
		// #1168: ルーティン（おふろ・はみがき 等）
		kind: 'routine',
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: 904,
		childId: 904,
		name: '中学生の登校準備',
		icon: '🎒',
		pointsPerItem: 3,
		completionBonus: 10,
		timeSlot: 'morning',
		isActive: 1,
		isArchived: 0,
		archivedReason: null,
		// #1168: 持ち物系（教科書・体操着・弁当 等の持ち物チェック）
		kind: 'item',
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: 905,
		childId: 906,
		name: '高校生の登校準備',
		icon: '📚',
		pointsPerItem: 3,
		completionBonus: 10,
		timeSlot: 'morning',
		isActive: 1,
		isArchived: 0,
		archivedReason: null,
		// #1168: 持ち物系
		kind: 'item',
		createdAt: NOW,
		updatedAt: NOW,
	},
];

export const DEMO_CHECKLIST_ITEMS: ChecklistTemplateItem[] = [
	// あさのしたく（morning-routine.json 準拠）
	{
		id: 1,
		templateId: 901,
		name: 'はみがき',
		icon: '🪥',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 1,
		createdAt: NOW,
	},
	{
		id: 2,
		templateId: 901,
		name: 'かおをあらう',
		icon: '🧼',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 2,
		createdAt: NOW,
	},
	{
		id: 3,
		templateId: 901,
		name: 'きがえ',
		icon: '👕',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 3,
		createdAt: NOW,
	},
	{
		id: 4,
		templateId: 901,
		name: 'あさごはん',
		icon: '🍚',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 4,
		createdAt: NOW,
	},
	{
		id: 5,
		templateId: 901,
		name: 'もちものチェック',
		icon: '🎒',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 5,
		createdAt: NOW,
	},
	// よるのじゅんび（evening-routine.json 準拠）
	{
		id: 6,
		templateId: 902,
		name: 'おふろ',
		icon: '🛁',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 1,
		createdAt: NOW,
	},
	{
		id: 7,
		templateId: 902,
		name: 'はみがき',
		icon: '🪥',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 2,
		createdAt: NOW,
	},
	{
		id: 8,
		templateId: 902,
		name: 'あしたのじゅんび',
		icon: '📋',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 3,
		createdAt: NOW,
	},
	{
		id: 9,
		templateId: 902,
		name: 'おやすみのあいさつ',
		icon: '😴',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 4,
		createdAt: NOW,
	},
	// #703: おでかけのじゅんび（たろう・乳幼児）
	{
		id: 20,
		templateId: 900,
		name: 'おむつ',
		icon: '👶',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 1,
		createdAt: NOW,
	},
	{
		id: 21,
		templateId: 900,
		name: 'おしりふき',
		icon: '🧻',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 2,
		createdAt: NOW,
	},
	{
		id: 22,
		templateId: 900,
		name: 'きがえ',
		icon: '👕',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 3,
		createdAt: NOW,
	},
	{
		id: 23,
		templateId: 900,
		name: 'ぼうし',
		icon: '🧢',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 4,
		createdAt: NOW,
	},
	{
		id: 24,
		templateId: 900,
		name: 'みずとう',
		icon: '🍼',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 5,
		createdAt: NOW,
	},
	// #703: 中学生の登校準備（さくら・中学生）
	{
		id: 30,
		templateId: 904,
		name: '教科書',
		icon: '📕',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 1,
		createdAt: NOW,
	},
	{
		id: 31,
		templateId: 904,
		name: 'ノート',
		icon: '📒',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 2,
		createdAt: NOW,
	},
	{
		id: 32,
		templateId: 904,
		name: '体操着',
		icon: '👕',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 3,
		createdAt: NOW,
	},
	{
		id: 33,
		templateId: 904,
		name: '制服',
		icon: '🎽',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 4,
		createdAt: NOW,
	},
	{
		id: 34,
		templateId: 904,
		name: 'お弁当',
		icon: '🍱',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 5,
		createdAt: NOW,
	},
	// #703: 高校生の登校準備（ゆうき・高校生）
	{
		id: 40,
		templateId: 905,
		name: '教科書',
		icon: '📕',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 1,
		createdAt: NOW,
	},
	{
		id: 41,
		templateId: 905,
		name: 'ノート',
		icon: '📒',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 2,
		createdAt: NOW,
	},
	{
		id: 42,
		templateId: 905,
		name: '参考書',
		icon: '📖',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 3,
		createdAt: NOW,
	},
	{
		id: 43,
		templateId: 905,
		name: 'お弁当',
		icon: '🍱',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 4,
		createdAt: NOW,
	},
	{
		id: 44,
		templateId: 905,
		name: 'ICカード',
		icon: '💳',
		frequency: 'daily',
		direction: 'positive',
		sortOrder: 5,
		createdAt: NOW,
	},
];

// ============================================================
// Login Bonus
// ============================================================

export const DEMO_LOGIN_BONUSES: LoginBonus[] = [
	// 902 はなこ (preschool)
	{
		id: 1,
		childId: 902,
		loginDate: TODAY,
		rank: 'dai-kichi',
		basePoints: 10,
		multiplier: 1.5,
		totalPoints: 15,
		consecutiveDays: 5,
		createdAt: NOW,
	},
	// 903 けんた (elementary)
	{
		id: 2,
		childId: 903,
		loginDate: TODAY,
		rank: 'kichi',
		basePoints: 5,
		multiplier: 2.0,
		totalPoints: 10,
		consecutiveDays: 14,
		createdAt: NOW,
	},
	// 904 さくら (junior)
	{
		id: 3,
		childId: 904,
		loginDate: TODAY,
		rank: 'chu-kichi',
		basePoints: 3,
		multiplier: 2.0,
		totalPoints: 6,
		consecutiveDays: 14,
		createdAt: NOW,
	},
];

// ============================================================
// Helper: Get demo data for a specific child
// ============================================================

export function getDemoActivitiesForChild(childAge: number): Activity[] {
	return DEMO_ACTIVITIES.filter(
		(a) =>
			(a.ageMin === null || childAge >= a.ageMin) && (a.ageMax === null || childAge <= a.ageMax),
	);
}

export function getDemoLogsForChild(childId: number): ActivityLog[] {
	return DEMO_ACTIVITY_LOGS.filter((l) => l.childId === childId);
}

export function getDemoStatusesForChild(childId: number): Status[] {
	return DEMO_STATUSES.filter((s) => s.childId === childId);
}

export function getDemoMissionsForChild(childId: number): DailyMission[] {
	return DEMO_DAILY_MISSIONS.filter((m) => m.childId === childId);
}

export function getDemoChecklistsForChild(childId: number): {
	templates: ChecklistTemplate[];
	items: ChecklistTemplateItem[];
} {
	const templates = DEMO_CHECKLIST_TEMPLATES.filter((t) => t.childId === childId);
	const templateIds = templates.map((t) => t.id);
	const items = DEMO_CHECKLIST_ITEMS.filter((i) => templateIds.includes(i.templateId));
	return { templates, items };
}

export function getDemoPointBalance(childId: number): number {
	return DEMO_POINT_BALANCES[childId] ?? 0;
}

export { DEMO_TENANT_ID, NOW, TODAY };
