// src/lib/server/db/seed.ts
// 初期データ投入スクリプト
// Usage: npx tsx src/lib/server/db/seed.ts

import bcrypt from 'bcrypt';
import Database from 'better-sqlite3';
import { eq } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import * as schema from './schema';

const DATABASE_URL = process.env.DATABASE_URL ?? './data/ganbari-quest.db';

const sqlite = new Database(DATABASE_URL);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');

const db = drizzle(sqlite, { schema });

function seed() {
	console.log('Seeding database...');

	// ============================================================
	// 初期子供データ
	// ============================================================
	const existingChildren = db.select().from(schema.children).all();
	if (existingChildren.length === 0) {
		db.insert(schema.children)
			.values({
				nickname: 'おじょうさま',
				age: 4,
				theme: 'pink',
				uiMode: 'kinder',
			})
			.run();
		console.log('  ✓ children: おじょうさま (4歳, kinder)');
	} else {
		console.log('  - children: already seeded');
	}

	// ============================================================
	// 活動マスタ（147件 — 学習指導要領準拠）
	// ============================================================
	const existingActivities = db.select().from(schema.activities).all();
	if (existingActivities.length === 0) {
		let sortIdx = 0;
		const s = () => ++sortIdx;
		const activitiesData: (typeof schema.activities.$inferInsert)[] = [
			// ============================
			// baby (0-2歳) — 保育所保育指針
			// ============================
			// うんどう
			{
				name: 'はいはいした',
				category: 'うんどう',
				icon: '🐣',
				basePoints: 3,
				ageMin: 0,
				ageMax: 1,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '粗大運動',
				description: '這う・立つなど基本的な運動機能の発達',
				sortOrder: s(),
			},
			{
				name: 'あんよした',
				category: 'うんどう',
				icon: '👣',
				basePoints: 5,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '粗大運動',
				description: '歩行の練習・伝い歩き',
				sortOrder: s(),
			},
			{
				name: 'おそとにでた',
				category: 'うんどう',
				icon: '🌿',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '外遊び',
				description: '戸外で外気に触れ体を動かす',
				sortOrder: s(),
			},
			{
				name: 'からだをうごかした',
				category: 'うんどう',
				icon: '🤸',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '全身運動',
				description: '伸び伸びと体を動かす遊び',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'えほんをみた',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: '絵本の読み聞かせを聞く',
				sortOrder: s(),
			},
			{
				name: 'おうたをきいた',
				category: 'べんきょう',
				icon: '🎵',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: 'わらべうた・手遊びうたを聞く',
				sortOrder: s(),
			},
			{
				name: 'ことばをまねた',
				category: 'べんきょう',
				icon: '🗣️',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: '喃語・片言の発語',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'ごはんをたべた',
				category: 'せいかつ',
				icon: '🍚',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '食事',
				description: '食事・離乳食を食べる',
				sortOrder: s(),
			},
			{
				name: 'ねんねできた',
				category: 'せいかつ',
				icon: '😴',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '睡眠',
				description: '規則正しい睡眠リズムの形成',
				sortOrder: s(),
			},
			{
				name: 'てをあらった',
				category: 'せいかつ',
				icon: '🧼',
				basePoints: 3,
				ageMin: 1,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '清潔',
				description: '手洗いの習慣づけ',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'にこにこした',
				category: 'こうりゅう',
				icon: '😊',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '愛着形成',
				description: '大人との応答的な関わり・微笑み返し',
				sortOrder: s(),
			},
			{
				name: 'バイバイした',
				category: 'こうりゅう',
				icon: '👋',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '挨拶',
				description: '手を振る・バイバイなどの身振り',
				sortOrder: s(),
			},
			{
				name: 'いないいないばあ',
				category: 'こうりゅう',
				icon: '🙈',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '遊び',
				description: '大人との関わり遊び',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'おもちゃであそんだ',
				category: 'そうぞう',
				icon: '🧸',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '感覚遊び',
				description: '様々な素材・玩具に触れる',
				sortOrder: s(),
			},
			{
				name: 'おとをならした',
				category: 'そうぞう',
				icon: '🔔',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '音遊び',
				description: '音の出るおもちゃ・楽器で遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'てあそびした',
				category: 'そうぞう',
				icon: '✋',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '手指遊び',
				description: 'つまむ・握るなどの手指を使う遊び',
				sortOrder: s(),
			},

			// ============================
			// kinder (3-5歳) — 幼稚園教育要領
			// ============================
			// うんどう
			{
				name: 'たいそうした',
				category: 'うんどう',
				icon: '🤸',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '体操',
				description: 'いろいろな遊びの中で十分に体を動かす',
				sortOrder: s(),
			},
			{
				name: 'おそとであそんだ',
				category: 'うんどう',
				icon: '🏃',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '外遊び',
				description: '進んで戸外で遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'すいみんぐ',
				category: 'うんどう',
				icon: '🏊',
				basePoints: 10,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '水遊び',
				description: '水に親しみ水遊びをする',
				sortOrder: s(),
			},
			{
				name: 'ボールあそび',
				category: 'うんどう',
				icon: '⚽',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '球技遊び',
				description: 'ボールを投げる・蹴る・転がす遊び',
				sortOrder: s(),
			},
			{
				name: 'おにごっこ',
				category: 'うんどう',
				icon: '🏷️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '走運動',
				description: '走る・追いかけるなどの全身運動遊び',
				sortOrder: s(),
			},
			{
				name: 'なわとびれんしゅう',
				category: 'うんどう',
				icon: '🪢',
				basePoints: 10,
				ageMin: 4,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '跳運動',
				description: 'なわとび・跳ぶ運動への挑戦',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'ひらがなれんしゅう',
				category: 'べんきょう',
				icon: '✏️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '文字',
				description: '文字で伝える楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'すうじをかぞえた',
				category: 'べんきょう',
				icon: '🔢',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '数量',
				description: '日常生活の中で数量や図形に関心をもつ',
				sortOrder: s(),
			},
			{
				name: 'えほんをよんだ',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '読書',
				description: '絵本や物語に親しみ想像する楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'としょかんにいった',
				category: 'べんきょう',
				icon: '🏛️',
				basePoints: 10,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '読書',
				description: '生活に関係の深い施設に興味をもつ',
				sortOrder: s(),
			},
			{
				name: 'しぜんをかんさつした',
				category: 'べんきょう',
				icon: '🔍',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '自然観察',
				description: '自然に触れ不思議さに気付く',
				sortOrder: s(),
			},
			{
				name: 'どうぶつ・しょくぶつのおせわ',
				category: 'べんきょう',
				icon: '🌱',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '飼育栽培',
				description: '身近な動植物に親しみ生命の尊さに気付く',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'おきがえした',
				category: 'せいかつ',
				icon: '👗',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '着替え',
				description: '衣服の着脱を自分でする',
				sortOrder: s(),
			},
			{
				name: 'はみがきした',
				category: 'せいかつ',
				icon: '🪥',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '清潔',
				description: '身の回りを清潔にする',
				sortOrder: s(),
			},
			{
				name: 'ごはんをぜんぶたべた',
				category: 'せいかつ',
				icon: '🍚',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '食事',
				description: '食べることを楽しみ残さず食べる',
				sortOrder: s(),
			},
			{
				name: 'おかたづけした',
				category: 'せいかつ',
				icon: '🧹',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '整頓',
				description: '生活の場を整える',
				sortOrder: s(),
			},
			{
				name: 'てあらい・うがいした',
				category: 'せいかつ',
				icon: '💧',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '清潔',
				description: '病気の予防に必要な活動を進んで行う',
				sortOrder: s(),
			},
			{
				name: 'はやねはやおきした',
				category: 'せいかつ',
				icon: '⏰',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '生活リズム',
				description: '健康な生活のリズムを身に付ける',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'ともだちとあそんだ',
				category: 'こうりゅう',
				icon: '🤝',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '友達関係',
				description: '友達と積極的にかかわり喜びを共感し合う',
				sortOrder: s(),
			},
			{
				name: 'あいさつした',
				category: 'こうりゅう',
				icon: '👋',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '挨拶',
				description: '親しみをもって日常のあいさつをする',
				sortOrder: s(),
			},
			{
				name: 'じぶんのきもちをつたえた',
				category: 'こうりゅう',
				icon: '💬',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '伝達',
				description: '自分の思ったことを相手に伝える',
				sortOrder: s(),
			},
			{
				name: 'おやくそくをまもった',
				category: 'こうりゅう',
				icon: '✅',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: 'ルール',
				description: 'きまりの大切さに気付き守ろうとする',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'おえかきした',
				category: 'そうぞう',
				icon: '🎨',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '絵画',
				description: '感じたことを自由にかく',
				sortOrder: s(),
			},
			{
				name: 'こうさくした',
				category: 'そうぞう',
				icon: '✂️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '工作',
				description: 'いろいろな素材に親しみ工夫して遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'うたをうたった',
				category: 'そうぞう',
				icon: '🎤',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '音楽',
				description: '音楽に親しみ歌を歌う楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'がっきであそんだ',
				category: 'そうぞう',
				icon: '🥁',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '音楽',
				description: '簡単なリズム楽器を使う楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'ダンス・おどり',
				category: 'そうぞう',
				icon: '💃',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '身体表現',
				description: '音や動きで表現する楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'ごっこあそび',
				category: 'そうぞう',
				icon: '🎭',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '劇遊び',
				description: 'イメージを動きや言葉で表現し演じて遊ぶ',
				sortOrder: s(),
			},

			// ============================
			// elementary_lower (6-9歳) — 小学校学習指導要領
			// ============================
			// うんどう
			{
				name: 'たいそう・ストレッチ',
				category: 'うんどう',
				icon: '🤸',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '体つくり運動',
				description: '体ほぐしの運動・多様な動きをつくる運動遊び',
				sortOrder: s(),
			},
			{
				name: 'かけっこ・おにごっこ',
				category: 'うんどう',
				icon: '🏃',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '走の運動遊び',
				description: '走の運動遊び・跳の運動遊び',
				sortOrder: s(),
			},
			{
				name: 'なわとび',
				category: 'うんどう',
				icon: '🪢',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '跳の運動遊び',
				description: '跳ぶ運動遊び・短なわ・長なわ',
				sortOrder: s(),
			},
			{
				name: 'マットうんどう',
				category: 'うんどう',
				icon: '🤾',
				basePoints: 10,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '器械運動遊び',
				description: 'マットを使っての運動遊び',
				sortOrder: s(),
			},
			{
				name: 'みずあそび・プール',
				category: 'うんどう',
				icon: '🏊',
				basePoints: 10,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '水遊び',
				description: '水に慣れる遊び・浮く・もぐる遊び',
				sortOrder: s(),
			},
			{
				name: 'ボールゲーム',
				category: 'うんどう',
				icon: '⚽',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: 'ゲーム',
				description: 'ボールゲーム・鬼遊び',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'こくごドリル',
				category: 'べんきょう',
				icon: '✏️',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '国語',
				description: 'ひらがな・カタカナ・漢字の読み書き練習',
				sortOrder: s(),
			},
			{
				name: 'さんすうドリル',
				category: 'べんきょう',
				icon: '🔢',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '算数',
				description: 'たし算・ひき算・かけ算の計算練習',
				sortOrder: s(),
			},
			{
				name: 'どくしょ（20ぷん）',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '読書',
				description: '読書習慣の形成・物語を楽しむ',
				sortOrder: s(),
			},
			{
				name: 'しぜんかんさつ',
				category: 'べんきょう',
				icon: '🔍',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活科',
				description: '自然や物を使った遊び・季節の観察',
				sortOrder: s(),
			},
			{
				name: 'どうぶつ・しょくぶつのせわ',
				category: 'べんきょう',
				icon: '🌱',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活科',
				description: '動植物の飼育・栽培',
				sortOrder: s(),
			},
			{
				name: 'にっきをかいた',
				category: 'べんきょう',
				icon: '📝',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '国語',
				description: '経験を文章に書く',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'はみがき・せいけつ',
				category: 'せいかつ',
				icon: '🪥',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '清潔',
				description: '健康な生活のリズム・清潔習慣',
				sortOrder: s(),
			},
			{
				name: 'はやねはやおき',
				category: 'せいかつ',
				icon: '⏰',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活リズム',
				description: '規則正しい生活リズム',
				sortOrder: s(),
			},
			{
				name: 'おてつだいした',
				category: 'せいかつ',
				icon: '🏠',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '家庭生活',
				description: '家庭での自分の役割を果たす',
				sortOrder: s(),
			},
			{
				name: 'じぶんのもちものをせいり',
				category: 'せいかつ',
				icon: '🎒',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '整頓',
				description: '持ち物の準備・整理整頓',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'あいさつ・へんじ',
				category: 'こうりゅう',
				icon: '👋',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '挨拶',
				description: '気持ちのよい挨拶と返事',
				sortOrder: s(),
			},
			{
				name: 'ともだちとなかよくした',
				category: 'こうりゅう',
				icon: '🤝',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '友達関係',
				description: '友達と仲よくし助け合う',
				sortOrder: s(),
			},
			{
				name: 'じぶんのかんがえをはなした',
				category: 'こうりゅう',
				icon: '💬',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '伝達',
				description: '自分の考えを話す・相手の話を聞く',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'リズムあそび・ダンス',
				category: 'そうぞう',
				icon: '💃',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '表現リズム',
				description: '表現遊び・リズム遊び',
				sortOrder: s(),
			},
			{
				name: 'おえかき・ずがこうさく',
				category: 'そうぞう',
				icon: '🎨',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '図画工作',
				description: '造形遊び・絵に表す活動',
				sortOrder: s(),
			},
			{
				name: 'こうさく',
				category: 'そうぞう',
				icon: '✂️',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '図画工作',
				description: '工作に表す活動・材料や用具の扱い',
				sortOrder: s(),
			},
			{
				name: 'うた・がっき',
				category: 'そうぞう',
				icon: '🎵',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '音楽',
				description: '歌唱・器楽の表現活動',
				sortOrder: s(),
			},
			{
				name: 'おんがくをきいた',
				category: 'そうぞう',
				icon: '🎧',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '音楽',
				description: '音楽鑑賞・リズムやメロディを楽しむ',
				sortOrder: s(),
			},

			// ============================
			// elementary_upper (10-12歳) — 小学校学習指導要領(高学年)
			// ============================
			// うんどう
			{
				name: '体つくり運動',
				category: 'うんどう',
				icon: '🏋️',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '体力向上',
				description: '体ほぐしの運動・体力を高める運動',
				sortOrder: s(),
			},
			{
				name: '短距離走・リレー',
				category: 'うんどう',
				icon: '🏃',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '陸上運動',
				description: '短距離走・リレー・ハードル走',
				sortOrder: s(),
			},
			{
				name: 'マット・跳び箱運動',
				category: 'うんどう',
				icon: '🤾',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '器械運動',
				description: 'マット運動・鉄棒運動・跳び箱運動',
				sortOrder: s(),
			},
			{
				name: '水泳（クロール・平泳ぎ）',
				category: 'うんどう',
				icon: '🏊',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '水泳',
				description: 'クロール・平泳ぎの技能向上',
				sortOrder: s(),
			},
			{
				name: 'ボール運動',
				category: 'うんどう',
				icon: '⚽',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型',
				sortOrder: s(),
			},
			{
				name: 'なわとびチャレンジ',
				category: 'うんどう',
				icon: '🪢',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '跳運動',
				description: '二重跳び・技の練習など発展的なわとび',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の自主学習',
				category: 'べんきょう',
				icon: '📝',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '国語',
				description: '漢字練習・読解・作文',
				sortOrder: s(),
			},
			{
				name: '算数の自主学習',
				category: 'べんきょう',
				icon: '🔢',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '算数',
				description: '計算・図形・文章題の家庭学習',
				sortOrder: s(),
			},
			{
				name: '読書（30分以上）',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '読書',
				description: '読書習慣の定着・多様なジャンルへの挑戦',
				sortOrder: s(),
			},
			{
				name: '理科の観察・実験記録',
				category: 'べんきょう',
				icon: '🔬',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '理科',
				description: '自然の観察記録・実験レポート',
				sortOrder: s(),
			},
			{
				name: '社会科の調べ学習',
				category: 'べんきょう',
				icon: '🗺️',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '社会',
				description: '地域・歴史・産業について調べる',
				sortOrder: s(),
			},
			{
				name: '英語の練習',
				category: 'べんきょう',
				icon: '🌍',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '外国語',
				description: 'アルファベット・基本表現の練習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '調理実習・料理のお手伝い',
				category: 'せいかつ',
				icon: '🍳',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: 'ゆでる・いためる調理の実践',
				sortOrder: s(),
			},
			{
				name: '洗濯・ボタン付け',
				category: 'せいかつ',
				icon: '🧵',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '衣服の手入れ・洗濯・裁縫',
				sortOrder: s(),
			},
			{
				name: '整理整頓・掃除',
				category: 'せいかつ',
				icon: '🧹',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '快適な住まい方・季節の工夫',
				sortOrder: s(),
			},
			{
				name: '家庭の仕事を分担',
				category: 'せいかつ',
				icon: '🏠',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '家庭生活の仕事と役割分担',
				sortOrder: s(),
			},
			{
				name: '時間の使い方を工夫',
				category: 'せいかつ',
				icon: '⏰',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '生活時間の有効な使い方',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'あいさつ・言葉遣い',
				category: 'こうりゅう',
				icon: '👋',
				basePoints: 3,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '礼儀',
				description: '時と場に応じた適切な言葉遣い',
				sortOrder: s(),
			},
			{
				name: '友達と協力して活動',
				category: 'こうりゅう',
				icon: '🤝',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '協力',
				description: '友達と互いに信頼し学び合い助け合う',
				sortOrder: s(),
			},
			{
				name: '委員会・係活動への貢献',
				category: 'こうりゅう',
				icon: '📋',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '特別活動',
				description: '学校での役割を主体的に果たす',
				sortOrder: s(),
			},
			{
				name: '地域の人への感謝',
				category: 'こうりゅう',
				icon: '🙏',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '地域',
				description: '地域の人々に感謝し共に生きる',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '絵画・デザイン制作',
				category: 'そうぞう',
				icon: '🎨',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '図画工作',
				description: '感じたことを絵や立体に表す',
				sortOrder: s(),
			},
			{
				name: '工作・ものづくり',
				category: 'そうぞう',
				icon: '🔨',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '図画工作',
				description: '用途を考えた工作・デザイン',
				sortOrder: s(),
			},
			{
				name: '合奏・楽器練習',
				category: 'そうぞう',
				icon: '🎹',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '音楽',
				description: 'リコーダー等の楽器演奏の練習',
				sortOrder: s(),
			},
			{
				name: '表現・フォークダンス',
				category: 'そうぞう',
				icon: '💃',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '表現運動',
				description: '表現・フォークダンス',
				sortOrder: s(),
			},
			{
				name: '裁縫・布を使った制作',
				category: 'そうぞう',
				icon: '🧵',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '手縫い・ミシンを用いた布製品の制作',
				sortOrder: s(),
			},

			// ============================
			// middle_school (13-15歳) — 中学校学習指導要領
			// ============================
			// うんどう
			{
				name: '体力トレーニング',
				category: 'うんどう',
				icon: '🏋️',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '体つくり',
				description: '体つくり運動・体力を高める運動の計画と実践',
				sortOrder: s(),
			},
			{
				name: 'ランニング・陸上練習',
				category: 'うんどう',
				icon: '🏃',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '陸上競技',
				description: '短距離走・長距離走・走り幅跳びなどの練習',
				sortOrder: s(),
			},
			{
				name: '水泳練習',
				category: 'うんどう',
				icon: '🏊',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '水泳',
				description: 'クロール・平泳ぎ・背泳ぎの技能向上',
				sortOrder: s(),
			},
			{
				name: '球技の練習',
				category: 'うんどう',
				icon: '⚽',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型の技能向上',
				sortOrder: s(),
			},
			{
				name: '武道の練習',
				category: 'うんどう',
				icon: '🥋',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '武道',
				description: '柔道・剣道・相撲など伝統的な運動文化',
				sortOrder: s(),
			},
			{
				name: '部活動の練習',
				category: 'うんどう',
				icon: '🏅',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '部活動',
				description: '運動部・文化部での主体的な活動',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の家庭学習',
				category: 'べんきょう',
				icon: '📝',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '国語',
				description: '漢字・文法・読解・作文の自主学習',
				sortOrder: s(),
			},
			{
				name: '数学の家庭学習',
				category: 'べんきょう',
				icon: '📐',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '数学',
				description: '方程式・関数・図形の演習',
				sortOrder: s(),
			},
			{
				name: '英語の家庭学習',
				category: 'べんきょう',
				icon: '🌍',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '英語',
				description: '単語・文法・リスニングの練習',
				sortOrder: s(),
			},
			{
				name: '理科の自主学習',
				category: 'べんきょう',
				icon: '🔬',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '理科',
				description: '実験レポート・科学的な観察記録',
				sortOrder: s(),
			},
			{
				name: '社会の自主学習',
				category: 'べんきょう',
				icon: '📚',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '社会',
				description: '歴史・地理・公民の調べ学習',
				sortOrder: s(),
			},
			{
				name: '読書（1時間）',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '読書',
				description: '幅広いジャンルの読書・読書感想文',
				sortOrder: s(),
			},
			{
				name: 'テスト勉強',
				category: 'べんきょう',
				icon: '🎯',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '試験対策',
				description: '定期テストに向けた計画的な学習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '調理実習の復習',
				category: 'せいかつ',
				icon: '🍳',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '日常食の調理と食事の仕方',
				sortOrder: s(),
			},
			{
				name: '家事の分担・実践',
				category: 'せいかつ',
				icon: '🏠',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '家庭の仕事を計画的に分担する',
				sortOrder: s(),
			},
			{
				name: '衣服の管理・手入れ',
				category: 'せいかつ',
				icon: '👕',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '衣服の選択・手入れ・洗濯',
				sortOrder: s(),
			},
			{
				name: '健康管理・生活改善',
				category: 'せいかつ',
				icon: '🩺',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '保健',
				description: '健康な生活と疾病の予防',
				sortOrder: s(),
			},
			{
				name: '金銭管理の実践',
				category: 'せいかつ',
				icon: '💰',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '消費生活と環境への配慮',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: '礼儀正しい言動',
				category: 'こうりゅう',
				icon: '🤝',
				basePoints: 3,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '礼儀',
				description: '礼儀の意義を理解し適切に行動する',
				sortOrder: s(),
			},
			{
				name: '友人との協力活動',
				category: 'こうりゅう',
				icon: '👥',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '友情',
				description: '友情を深め互いに切磋琢磨する',
				sortOrder: s(),
			},
			{
				name: '地域ボランティア',
				category: 'こうりゅう',
				icon: '🌐',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '社会貢献',
				description: '社会参画・勤労への意欲',
				sortOrder: s(),
			},
			{
				name: '進路について考えた',
				category: 'こうりゅう',
				icon: '🎓',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '進路',
				description: '将来の生き方・進路選択について考える',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '美術作品の制作',
				category: 'そうぞう',
				icon: '🎨',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '美術',
				description: '感じ取ったことを絵や彫刻で表現する',
				sortOrder: s(),
			},
			{
				name: '音楽の練習（歌唱・器楽）',
				category: 'そうぞう',
				icon: '🎵',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '音楽',
				description: '歌唱・器楽の表現技能の向上',
				sortOrder: s(),
			},
			{
				name: '技術ものづくり',
				category: 'そうぞう',
				icon: '🔧',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術',
				description: '材料と加工の技術・プログラミング',
				sortOrder: s(),
			},
			{
				name: 'ダンス・創作表現',
				category: 'そうぞう',
				icon: '💃',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: 'ダンス',
				description: '創作ダンス・フォークダンス・現代的なリズムのダンス',
				sortOrder: s(),
			},
			{
				name: '作文・レポート執筆',
				category: 'そうぞう',
				icon: '✍️',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '国語',
				description: '論理的な文章を書く力の育成',
				sortOrder: s(),
			},

			// ============================
			// high_school (16-18歳) — 高等学校学習指導要領
			// ============================
			// うんどう
			{
				name: '体力づくり・筋トレ',
				category: 'うんどう',
				icon: '🏋️',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '体つくり',
				description: '体つくり運動・自己の体力課題に応じた運動',
				sortOrder: s(),
			},
			{
				name: 'ランニング・ジョギング',
				category: 'うんどう',
				icon: '🏃',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '陸上',
				description: '陸上競技・持久走など',
				sortOrder: s(),
			},
			{
				name: '球技・スポーツ活動',
				category: 'うんどう',
				icon: '⚽',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型の発展的な活動',
				sortOrder: s(),
			},
			{
				name: '武道・ダンス',
				category: 'うんどう',
				icon: '🥋',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '武道/ダンス',
				description: '伝統的な武道またはダンスの選択',
				sortOrder: s(),
			},
			{
				name: '部活動・クラブ活動',
				category: 'うんどう',
				icon: '🏅',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '部活動',
				description: '運動部・文化部での主体的な取り組み',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の自主学習（高校）',
				category: 'べんきょう',
				icon: '📝',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国語',
				description: '現代文・古文・漢文の学習',
				sortOrder: s(),
			},
			{
				name: '数学の自主学習',
				category: 'べんきょう',
				icon: '📐',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '数学',
				description: '数学I/II/III/A/Bの演習',
				sortOrder: s(),
			},
			{
				name: '英語の自主学習（高校）',
				category: 'べんきょう',
				icon: '🌍',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '英語',
				description: '英語コミュニケーション・論理英語の学習',
				sortOrder: s(),
			},
			{
				name: '理科の自主学習（高校）',
				category: 'べんきょう',
				icon: '🔬',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '理科',
				description: '物理・化学・生物・地学の学習と実験',
				sortOrder: s(),
			},
			{
				name: '社会科の自主学習（高校）',
				category: 'べんきょう',
				icon: '📚',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '社会',
				description: '地理歴史・公民の学習',
				sortOrder: s(),
			},
			{
				name: '読書・論文読解',
				category: 'べんきょう',
				icon: '📖',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '読書',
				description: '多様な文章の読解・批評的な読み',
				sortOrder: s(),
			},
			{
				name: '受験勉強・模試対策',
				category: 'べんきょう',
				icon: '🎯',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '受験',
				description: '進路実現に向けた計画的な学習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '食事の自立（献立・調理）',
				category: 'せいかつ',
				icon: '🍳',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '栄養バランスを考えた献立と調理実践',
				sortOrder: s(),
			},
			{
				name: '家事の自立的実践',
				category: 'せいかつ',
				icon: '🏠',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '自立した生活者として家事を計画・実践',
				sortOrder: s(),
			},
			{
				name: '金銭管理・消費行動',
				category: 'せいかつ',
				icon: '💰',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '消費生活・金銭管理・消費者の権利と責任',
				sortOrder: s(),
			},
			{
				name: '健康管理・ストレス対処',
				category: 'せいかつ',
				icon: '🩺',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '保健',
				description: '精神疾患の予防・ストレスへの対処',
				sortOrder: s(),
			},
			{
				name: '環境に配慮した生活',
				category: 'せいかつ',
				icon: '♻️',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '持続可能な社会を目指す生活の工夫',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: '社会貢献・ボランティア',
				category: 'こうりゅう',
				icon: '🌐',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '社会参画',
				description: '社会参画の意識と実践',
				sortOrder: s(),
			},
			{
				name: '進路研究・キャリア設計',
				category: 'こうりゅう',
				icon: '🎓',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '進路',
				description: '自己の在り方生き方と進路選択',
				sortOrder: s(),
			},
			{
				name: 'プレゼンテーション',
				category: 'こうりゅう',
				icon: '🎤',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '表現',
				description: '自分の考えを論理的に伝える',
				sortOrder: s(),
			},
			{
				name: '異文化交流・国際理解',
				category: 'こうりゅう',
				icon: '🌏',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国際',
				description: '国際理解・異文化コミュニケーション',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '美術・デザイン制作',
				category: 'そうぞう',
				icon: '🎨',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '美術',
				description: '主題に応じた絵画・彫刻・デザインの制作',
				sortOrder: s(),
			},
			{
				name: '音楽活動（歌唱・楽器・作曲）',
				category: 'そうぞう',
				icon: '🎵',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '音楽',
				description: '歌唱・器楽・創作の表現活動',
				sortOrder: s(),
			},
			{
				name: '創作文・小論文執筆',
				category: 'そうぞう',
				icon: '✍️',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国語',
				description: '創造的な文章・論理的な小論文の執筆',
				sortOrder: s(),
			},
			{
				name: 'プログラミング・情報制作',
				category: 'そうぞう',
				icon: '💻',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '情報',
				description: 'プログラミング・情報デザイン',
				sortOrder: s(),
			},
			{
				name: '探究レポート・研究発表',
				category: 'そうぞう',
				icon: '📊',
				basePoints: 20,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '探究',
				description: '探究課題の研究成果をまとめ発表する',
				sortOrder: s(),
			},
		];

		db.insert(schema.activities).values(activitiesData).run();
		console.log(`  ✓ activities: ${activitiesData.length} items (学習指導要領準拠)`);
	} else {
		console.log('  - activities: already seeded');
	}

	// ============================================================
	// 初期市場ベンチマーク（4歳児・暫定値）
	// ============================================================
	const existingBenchmarks = db.select().from(schema.marketBenchmarks).all();
	if (existingBenchmarks.length === 0) {
		const benchmarksData: (typeof schema.marketBenchmarks.$inferInsert)[] = [
			{ age: 4, category: 'うんどう', mean: 30.0, stdDev: 10.0, source: '暫定値' },
			{ age: 4, category: 'べんきょう', mean: 20.0, stdDev: 8.0, source: '暫定値' },
			{ age: 4, category: 'せいかつ', mean: 35.0, stdDev: 8.0, source: '暫定値' },
			{ age: 4, category: 'こうりゅう', mean: 25.0, stdDev: 10.0, source: '暫定値' },
			{ age: 4, category: 'そうぞう', mean: 25.0, stdDev: 9.0, source: '暫定値' },
		];

		db.insert(schema.marketBenchmarks).values(benchmarksData).run();
		console.log(`  ✓ market_benchmarks: ${benchmarksData.length} items`);
	} else {
		console.log('  - market_benchmarks: already seeded');
	}

	// ============================================================
	// 初期ステータス（おじょうさま・市場平均値で初期化）
	// ============================================================
	const existingStatuses = db.select().from(schema.statuses).all();
	if (existingStatuses.length === 0) {
		const statusesData: (typeof schema.statuses.$inferInsert)[] = [
			{ childId: 1, category: 'うんどう', value: 30.0 },
			{ childId: 1, category: 'べんきょう', value: 20.0 },
			{ childId: 1, category: 'せいかつ', value: 35.0 },
			{ childId: 1, category: 'こうりゅう', value: 25.0 },
			{ childId: 1, category: 'そうぞう', value: 25.0 },
		];

		db.insert(schema.statuses).values(statusesData).run();
		console.log(`  ✓ statuses: ${statusesData.length} items`);
	} else {
		console.log('  - statuses: already seeded');
	}

	// ============================================================
	// 初期実績マスタ（12件）
	// ============================================================
	const existingAchievements = db.select().from(schema.achievements).all();
	if (existingAchievements.length === 0) {
		const achievementsData: (typeof schema.achievements.$inferInsert)[] = [
			{
				code: 'first_activity',
				name: 'はじめてのきろく',
				description: 'はじめてかつどうをきろくした！',
				icon: '🌟',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 1,
				bonusPoints: 10,
				rarity: 'common',
				sortOrder: 1,
			},
			{
				code: 'streak_3',
				name: '3にちれんぞく',
				description: '3にちれんぞくでかつどうした！',
				icon: '🔥',
				category: null,
				conditionType: 'streak_days',
				conditionValue: 3,
				bonusPoints: 20,
				rarity: 'common',
				sortOrder: 2,
			},
			{
				code: 'streak_7',
				name: '7にちれんぞく',
				description: '1しゅうかんれんぞくでかつどうした！',
				icon: '💪',
				category: null,
				conditionType: 'streak_days',
				conditionValue: 7,
				bonusPoints: 50,
				rarity: 'rare',
				sortOrder: 3,
			},
			{
				code: 'streak_30',
				name: '30にちれんぞく',
				description: '1かげつれんぞくでかつどうした！',
				icon: '👑',
				category: null,
				conditionType: 'streak_days',
				conditionValue: 30,
				bonusPoints: 200,
				rarity: 'epic',
				sortOrder: 4,
			},
			{
				code: 'activities_10',
				name: '10かいきろく',
				description: '10かいかつどうをきろくした！',
				icon: '📝',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 10,
				bonusPoints: 30,
				rarity: 'common',
				sortOrder: 5,
			},
			{
				code: 'activities_50',
				name: '50かいきろく',
				description: '50かいかつどうをきろくした！',
				icon: '📚',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 50,
				bonusPoints: 100,
				rarity: 'rare',
				sortOrder: 6,
			},
			{
				code: 'activities_100',
				name: '100かいきろく',
				description: '100かいかつどうをきろくした！',
				icon: '🏆',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 100,
				bonusPoints: 300,
				rarity: 'epic',
				sortOrder: 7,
			},
			{
				code: 'all_categories',
				name: 'ぜんぶのカテゴリ',
				description: '1にちですべてのカテゴリをきろくした！',
				icon: '🌈',
				category: null,
				conditionType: 'all_categories',
				conditionValue: 1,
				bonusPoints: 50,
				rarity: 'rare',
				sortOrder: 8,
			},
			{
				code: 'level_5',
				name: 'レベル5とうたつ',
				description: 'レベル5になった！',
				icon: '⭐',
				category: null,
				conditionType: 'level_reach',
				conditionValue: 5,
				bonusPoints: 100,
				rarity: 'rare',
				sortOrder: 9,
			},
			{
				code: 'level_10',
				name: 'さいきょうレベル',
				description: 'レベル10になった！すごい！',
				icon: '💎',
				category: null,
				conditionType: 'level_reach',
				conditionValue: 10,
				bonusPoints: 500,
				rarity: 'legendary',
				sortOrder: 10,
			},
			{
				code: 'points_100',
				name: '100ポイントたっせい',
				description: 'ごうけい100ポイントたまった！',
				icon: '💰',
				category: null,
				conditionType: 'total_points',
				conditionValue: 100,
				bonusPoints: 30,
				rarity: 'common',
				sortOrder: 11,
			},
			{
				code: 'points_1000',
				name: '1000ポイントたっせい',
				description: 'ごうけい1000ポイントたまった！',
				icon: '🤑',
				category: null,
				conditionType: 'total_points',
				conditionValue: 1000,
				bonusPoints: 200,
				rarity: 'epic',
				sortOrder: 12,
			},
		];

		db.insert(schema.achievements).values(achievementsData).run();
		console.log(`  ✓ achievements: ${achievementsData.length} items`);
	} else {
		console.log('  - achievements: already seeded');
	}

	// ============================================================
	// 初期設定（PIN認証用）
	// ============================================================
	const existingSettings = db.select().from(schema.settings).all();
	if (existingSettings.length === 0) {
		const defaultPinHash = bcrypt.hashSync('1234', 10);
		db.insert(schema.settings)
			.values([
				{ key: 'pin_hash', value: defaultPinHash },
				{ key: 'session_token', value: '' },
				{ key: 'session_expires_at', value: '' },
				{ key: 'pin_failed_attempts', value: '0' },
				{ key: 'pin_locked_until', value: '' },
			])
			.run();
		console.log('  ✓ settings: PIN auth defaults (デフォルトPIN: 1234)');
	} else {
		console.log('  - settings: already seeded');
	}

	// ============================================================
	// 特別報酬テンプレート（settingsにJSON保存）
	// ============================================================
	const existingTemplates = db
		.select()
		.from(schema.settings)
		.where(eq(schema.settings.key, 'reward_templates'))
		.get();
	if (!existingTemplates) {
		const templates = [
			{ title: 'テスト100てん', points: 100, icon: '🎓', category: 'academic' },
			{ title: 'しかくごうかく', points: 200, icon: '📜', category: 'academic' },
			{ title: 'うんどうかい1い', points: 150, icon: '🏆', category: 'sports' },
			{ title: 'はっぴょうかいがんばった', points: 100, icon: '🎤', category: 'social' },
			{ title: 'さくひんにゅうしょう', points: 150, icon: '🎨', category: 'creative' },
			{ title: 'おてつだいありがとう', points: 50, icon: '🙏', category: 'life' },
		];
		db.insert(schema.settings)
			.values({ key: 'reward_templates', value: JSON.stringify(templates) })
			.run();
		console.log(`  ✓ reward_templates: ${templates.length} templates`);
	} else {
		console.log('  - reward_templates: already seeded');
	}

	console.log('Seeding complete!');
}

seed();
sqlite.close();
