// src/lib/server/db/seed.ts
// 初期データ投入スクリプト
// Usage: npx tsx src/lib/server/db/seed.ts

import Database from 'better-sqlite3';
import { and, eq } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import * as schema from './schema';

const DATABASE_URL = process.env.DATABASE_URL ?? './data/ganbari-quest.db';

const sqlite = new Database(DATABASE_URL);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');

const db = drizzle(sqlite, { schema });

function seed() {
	console.log('Seeding database...');

	// ============================================================
	// 活動マスタ（174件 — 学習指導要領準拠 + 家事スキル）
	// ============================================================
	const existingActivities = db.select().from(schema.activities).all();
	if (existingActivities.length === 0) {
		let sortIdx = 0;
		const s = () => ++sortIdx;
		const activitiesData: (typeof schema.activities.$inferInsert)[] = [
			// ============================
			// baby (0-2歳) — 保育所保育指針
			// ============================
			// うんどう
			{
				name: 'はいはいした',
				categoryId: 1,
				icon: '🐣',
				basePoints: 3,
				ageMin: 0,
				ageMax: 1,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '粗大運動',
				description: '這う・立つなど基本的な運動機能の発達',
				sortOrder: s(),
			},
			{
				name: 'あんよした',
				categoryId: 1,
				icon: '👣',
				basePoints: 5,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '粗大運動',
				description: '歩行の練習・伝い歩き',
				sortOrder: s(),
			},
			{
				name: 'おそとにでた',
				categoryId: 1,
				icon: '🌿',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '外遊び',
				description: '戸外で外気に触れ体を動かす',
				sortOrder: s(),
			},
			{
				name: 'からだをうごかした',
				categoryId: 1,
				icon: '🤸',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '全身運動',
				description: '伸び伸びと体を動かす遊び',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'えほんをみた',
				categoryId: 2,
				icon: '📖',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: '絵本の読み聞かせを聞く',
				sortOrder: s(),
			},
			{
				name: 'おうたをきいた',
				categoryId: 2,
				icon: '🎵',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: 'わらべうた・手遊びうたを聞く',
				sortOrder: s(),
			},
			{
				name: 'ことばをまねた',
				categoryId: 2,
				icon: '🗣️',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '言葉',
				description: '喃語・片言の発語',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'ごはんをたべた',
				categoryId: 3,
				icon: '🍚',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '食事',
				description: '食事・離乳食を食べる',
				dailyLimit: 3,
				sortOrder: s(),
			},
			{
				name: 'ねんねできた',
				categoryId: 3,
				icon: '😴',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '睡眠',
				description: '規則正しい睡眠リズムの形成',
				sortOrder: s(),
			},
			{
				name: 'てをあらった',
				categoryId: 3,
				icon: '🤲💧',
				basePoints: 3,
				ageMin: 1,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '清潔',
				description: '手洗いの習慣づけ',
				dailyLimit: 3,
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'にこにこした',
				categoryId: 4,
				icon: '😊',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '愛着形成',
				description: '大人との応答的な関わり・微笑み返し',
				sortOrder: s(),
			},
			{
				name: 'バイバイした',
				categoryId: 4,
				icon: '👋',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '挨拶',
				description: '手を振る・バイバイなどの身振り',
				sortOrder: s(),
			},
			{
				name: 'いないいないばあ',
				categoryId: 4,
				icon: '🙈',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '遊び',
				description: '大人との関わり遊び',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'おもちゃであそんだ',
				categoryId: 5,
				icon: '🧸',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '感覚遊び',
				description: '様々な素材・玩具に触れる',
				sortOrder: s(),
			},
			{
				name: 'おとをならした',
				categoryId: 5,
				icon: '🔔',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '音遊び',
				description: '音の出るおもちゃ・楽器で遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'てあそびした',
				categoryId: 5,
				icon: '✋',
				basePoints: 3,
				ageMin: 0,
				ageMax: 2,
				source: 'curriculum',
				gradeLevel: 'baby',
				subcategory: '手指遊び',
				description: 'つまむ・握るなどの手指を使う遊び',
				sortOrder: s(),
			},

			// ============================
			// kinder (3-5歳) — 幼稚園教育要領
			// ============================
			// うんどう
			{
				name: 'たいそうした',
				categoryId: 1,
				icon: '🤸',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '体操',
				description: 'いろいろな遊びの中で十分に体を動かす',
				sortOrder: s(),
			},
			{
				name: 'おそとであそんだ',
				categoryId: 1,
				icon: '🏃',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '外遊び',
				description: '進んで戸外で遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'すいみんぐ',
				categoryId: 1,
				icon: '🏊',
				basePoints: 10,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '水遊び',
				description: '水に親しみ水遊びをする',
				sortOrder: s(),
			},
			{
				name: 'ボールあそび',
				categoryId: 1,
				icon: '⚽',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '球技遊び',
				description: 'ボールを投げる・蹴る・転がす遊び',
				sortOrder: s(),
			},
			{
				name: 'おにごっこ',
				categoryId: 1,
				icon: '🏷️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '走運動',
				description: '走る・追いかけるなどの全身運動遊び',
				sortOrder: s(),
			},
			{
				name: 'なわとびれんしゅう',
				categoryId: 1,
				icon: '🪢',
				basePoints: 10,
				ageMin: 4,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '跳運動',
				description: 'なわとび・跳ぶ運動への挑戦',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'ひらがなれんしゅう',
				categoryId: 2,
				icon: '✏️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '文字',
				description: '文字で伝える楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'すうじをかぞえた',
				categoryId: 2,
				icon: '🔢',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '数量',
				description: '日常生活の中で数量や図形に関心をもつ',
				sortOrder: s(),
			},
			{
				name: 'えほんをよんだ',
				categoryId: 2,
				icon: '📖',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '読書',
				description: '絵本や物語に親しみ想像する楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'としょかんにいった',
				categoryId: 2,
				icon: '🏛️',
				basePoints: 10,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '読書',
				description: '生活に関係の深い施設に興味をもつ',
				sortOrder: s(),
			},
			{
				name: 'しぜんをかんさつした',
				categoryId: 2,
				icon: '🔍',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '自然観察',
				description: '自然に触れ不思議さに気付く',
				sortOrder: s(),
			},
			{
				name: 'どうぶつ・しょくぶつのおせわ',
				categoryId: 2,
				icon: '🌱',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '飼育栽培',
				description: '身近な動植物に親しみ生命の尊さに気付く',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'おきがえした',
				categoryId: 3,
				icon: '👗',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '着替え',
				description: '衣服の着脱を自分でする',
				sortOrder: s(),
			},
			{
				name: 'はみがきした',
				categoryId: 3,
				icon: '🪥',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '清潔',
				description: '身の回りを清潔にする',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'ごはんをぜんぶたべた',
				categoryId: 3,
				icon: '🍚',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '食事',
				description: '食べることを楽しみ残さず食べる',
				dailyLimit: 3,
				sortOrder: s(),
			},
			{
				name: 'おかたづけした',
				categoryId: 3,
				icon: '🧹✨',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '整頓',
				description: '生活の場を整える',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'てあらい・うがいした',
				categoryId: 3,
				icon: '🤲💧',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '清潔',
				description: '病気の予防に必要な活動を進んで行う',
				dailyLimit: 3,
				sortOrder: s(),
			},
			{
				name: 'はやねはやおきした',
				categoryId: 3,
				icon: '⏰',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '生活リズム',
				description: '健康な生活のリズムを身に付ける',
				sortOrder: s(),
			},
			{
				name: 'もちものチェックした',
				categoryId: 3,
				icon: '🎒✅',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'seed',
				gradeLevel: 'kinder',
				subcategory: '準備',
				description: 'あしたのもちものをたしかめた',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'ともだちとあそんだ',
				categoryId: 4,
				icon: '🤝',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '友達関係',
				description: '友達と積極的にかかわり喜びを共感し合う',
				sortOrder: s(),
			},
			{
				name: 'あいさつした',
				categoryId: 4,
				icon: '👋',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '挨拶',
				description: '親しみをもって日常のあいさつをする',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'じぶんのきもちをつたえた',
				categoryId: 4,
				icon: '💬',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '伝達',
				description: '自分の思ったことを相手に伝える',
				sortOrder: s(),
			},
			{
				name: 'おやくそくをまもった',
				categoryId: 4,
				icon: '✅',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: 'ルール',
				description: 'きまりの大切さに気付き守ろうとする',
				sortOrder: s(),
			},
			{
				name: 'せんせいとおはなしした',
				categoryId: 4,
				icon: '👩‍🏫',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'seed',
				gradeLevel: 'kinder',
				subcategory: '伝達',
				description: '先生に自分のことを話したり質問したりする',
				sortOrder: s(),
			},
			{
				name: 'いっしょにごはんたべた',
				categoryId: 4,
				icon: '🍽️👫',
				basePoints: 2,
				ageMin: 3,
				ageMax: 5,
				source: 'seed',
				gradeLevel: 'kinder',
				subcategory: '食事',
				description: '家族や友達と一緒に楽しく食事する',
				sortOrder: s(),
			},
			{
				name: 'おてがみをかいた',
				categoryId: 4,
				icon: '✉️',
				basePoints: 3,
				ageMin: 3,
				ageMax: 5,
				source: 'seed',
				gradeLevel: 'kinder',
				subcategory: '伝達',
				description: '友達や家族にお手紙やカードを書く',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'おえかきした',
				categoryId: 5,
				icon: '🎨',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '絵画',
				description: '感じたことを自由にかく',
				sortOrder: s(),
			},
			{
				name: 'こうさくした',
				categoryId: 5,
				icon: '✂️',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '工作',
				description: 'いろいろな素材に親しみ工夫して遊ぶ',
				sortOrder: s(),
			},
			{
				name: 'うたをうたった',
				categoryId: 5,
				icon: '🎤',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '音楽',
				description: '音楽に親しみ歌を歌う楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'がっきであそんだ',
				categoryId: 5,
				icon: '🥁',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '音楽',
				description: '簡単なリズム楽器を使う楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'ダンス・おどり',
				categoryId: 5,
				icon: '💃',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '身体表現',
				description: '音や動きで表現する楽しさを味わう',
				sortOrder: s(),
			},
			{
				name: 'ごっこあそび',
				categoryId: 5,
				icon: '🎭',
				basePoints: 5,
				ageMin: 3,
				ageMax: 5,
				source: 'curriculum',
				gradeLevel: 'kinder',
				subcategory: '劇遊び',
				description: 'イメージを動きや言葉で表現し演じて遊ぶ',
				sortOrder: s(),
			},

			// ============================
			// elementary_lower (6-9歳) — 小学校学習指導要領
			// ============================
			// うんどう
			{
				name: 'たいそう・ストレッチ',
				categoryId: 1,
				icon: '🤸',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '体つくり運動',
				description: '体ほぐしの運動・多様な動きをつくる運動遊び',
				sortOrder: s(),
			},
			{
				name: 'かけっこ・おにごっこ',
				categoryId: 1,
				icon: '🏃',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '走の運動遊び',
				description: '走の運動遊び・跳の運動遊び',
				sortOrder: s(),
			},
			{
				name: 'なわとび',
				categoryId: 1,
				icon: '🪢',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '跳の運動遊び',
				description: '跳ぶ運動遊び・短なわ・長なわ',
				sortOrder: s(),
			},
			{
				name: 'マットうんどう',
				categoryId: 1,
				icon: '🤾',
				basePoints: 10,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '器械運動遊び',
				description: 'マットを使っての運動遊び',
				sortOrder: s(),
			},
			{
				name: 'みずあそび・プール',
				categoryId: 1,
				icon: '🏊',
				basePoints: 10,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '水遊び',
				description: '水に慣れる遊び・浮く・もぐる遊び',
				sortOrder: s(),
			},
			{
				name: 'ボールゲーム',
				categoryId: 1,
				icon: '⚽',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: 'ゲーム',
				description: 'ボールゲーム・鬼遊び',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: 'こくごドリル',
				categoryId: 2,
				icon: '✏️',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '国語',
				description: 'ひらがな・カタカナ・漢字の読み書き練習',
				sortOrder: s(),
			},
			{
				name: 'さんすうドリル',
				categoryId: 2,
				icon: '🔢',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '算数',
				description: 'たし算・ひき算・かけ算の計算練習',
				sortOrder: s(),
			},
			{
				name: 'どくしょ（20ぷん）',
				categoryId: 2,
				icon: '📖',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '読書',
				description: '読書習慣の形成・物語を楽しむ',
				sortOrder: s(),
			},
			{
				name: 'しぜんかんさつ',
				categoryId: 2,
				icon: '🔍',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活科',
				description: '自然や物を使った遊び・季節の観察',
				sortOrder: s(),
			},
			{
				name: 'どうぶつ・しょくぶつのせわ',
				categoryId: 2,
				icon: '🌱',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活科',
				description: '動植物の飼育・栽培',
				sortOrder: s(),
			},
			{
				name: 'にっきをかいた',
				categoryId: 2,
				icon: '📝',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '国語',
				description: '経験を文章に書く',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: 'はみがき・せいけつ',
				categoryId: 3,
				icon: '🪥',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '清潔',
				description: '健康な生活のリズム・清潔習慣',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'はやねはやおき',
				categoryId: 3,
				icon: '⏰',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '生活リズム',
				description: '規則正しい生活リズム',
				sortOrder: s(),
			},
			{
				name: 'おてつだいした',
				categoryId: 3,
				icon: '🏠',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '家庭生活',
				description: '家庭での自分の役割を果たす',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'じぶんのもちものをせいり',
				categoryId: 3,
				icon: '🎒',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '整頓',
				description: '持ち物の準備・整理整頓',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'あしたのじゅんびした',
				categoryId: 3,
				icon: '🎒📝',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'seed',
				gradeLevel: 'elementary_lower',
				subcategory: '準備',
				description: 'ランドセルの中身・持ち物を確認した',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'あいさつ・へんじ',
				categoryId: 4,
				icon: '👋',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '挨拶',
				description: '気持ちのよい挨拶と返事',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: 'ともだちとなかよくした',
				categoryId: 4,
				icon: '🤝',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '友達関係',
				description: '友達と仲よくし助け合う',
				sortOrder: s(),
			},
			{
				name: 'じぶんのかんがえをはなした',
				categoryId: 4,
				icon: '💬',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '伝達',
				description: '自分の考えを話す・相手の話を聞く',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: 'リズムあそび・ダンス',
				categoryId: 5,
				icon: '💃',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '表現リズム',
				description: '表現遊び・リズム遊び',
				sortOrder: s(),
			},
			{
				name: 'おえかき・ずがこうさく',
				categoryId: 5,
				icon: '🎨',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '図画工作',
				description: '造形遊び・絵に表す活動',
				sortOrder: s(),
			},
			{
				name: 'こうさく',
				categoryId: 5,
				icon: '✂️',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '図画工作',
				description: '工作に表す活動・材料や用具の扱い',
				sortOrder: s(),
			},
			{
				name: 'うた・がっき',
				categoryId: 5,
				icon: '🎵',
				basePoints: 5,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '音楽',
				description: '歌唱・器楽の表現活動',
				sortOrder: s(),
			},
			{
				name: 'おんがくをきいた',
				categoryId: 5,
				icon: '🎧',
				basePoints: 3,
				ageMin: 6,
				ageMax: 9,
				source: 'curriculum',
				gradeLevel: 'elementary_lower',
				subcategory: '音楽',
				description: '音楽鑑賞・リズムやメロディを楽しむ',
				sortOrder: s(),
			},

			// ============================
			// elementary_upper (10-12歳) — 小学校学習指導要領(高学年)
			// ============================
			// うんどう
			{
				name: '体つくり運動',
				categoryId: 1,
				icon: '🏋️',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '体力向上',
				description: '体ほぐしの運動・体力を高める運動',
				sortOrder: s(),
			},
			{
				name: '短距離走・リレー',
				categoryId: 1,
				icon: '🏃',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '陸上運動',
				description: '短距離走・リレー・ハードル走',
				sortOrder: s(),
			},
			{
				name: 'マット・跳び箱運動',
				categoryId: 1,
				icon: '🤾',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '器械運動',
				description: 'マット運動・鉄棒運動・跳び箱運動',
				sortOrder: s(),
			},
			{
				name: '水泳（クロール・平泳ぎ）',
				categoryId: 1,
				icon: '🏊',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '水泳',
				description: 'クロール・平泳ぎの技能向上',
				sortOrder: s(),
			},
			{
				name: 'ボール運動',
				categoryId: 1,
				icon: '⚽',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型',
				sortOrder: s(),
			},
			{
				name: 'なわとびチャレンジ',
				categoryId: 1,
				icon: '🪢',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '跳運動',
				description: '二重跳び・技の練習など発展的なわとび',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の自主学習',
				categoryId: 2,
				icon: '📝',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '国語',
				description: '漢字練習・読解・作文',
				sortOrder: s(),
			},
			{
				name: '算数の自主学習',
				categoryId: 2,
				icon: '🔢',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '算数',
				description: '計算・図形・文章題の家庭学習',
				sortOrder: s(),
			},
			{
				name: '読書（30分以上）',
				categoryId: 2,
				icon: '📖',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '読書',
				description: '読書習慣の定着・多様なジャンルへの挑戦',
				sortOrder: s(),
			},
			{
				name: '理科の観察・実験記録',
				categoryId: 2,
				icon: '🔬',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '理科',
				description: '自然の観察記録・実験レポート',
				sortOrder: s(),
			},
			{
				name: '社会科の調べ学習',
				categoryId: 2,
				icon: '🗺️',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '社会',
				description: '地域・歴史・産業について調べる',
				sortOrder: s(),
			},
			{
				name: '英語の練習',
				categoryId: 2,
				icon: '🌍',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '外国語',
				description: 'アルファベット・基本表現の練習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '調理実習・料理のお手伝い',
				categoryId: 3,
				icon: '🍳',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: 'ゆでる・いためる調理の実践',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '洗濯・ボタン付け',
				categoryId: 3,
				icon: '🧵',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '衣服の手入れ・洗濯・裁縫',
				sortOrder: s(),
			},
			{
				name: '整理整頓・掃除',
				categoryId: 3,
				icon: '🧹',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '快適な住まい方・季節の工夫',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '家庭の仕事を分担',
				categoryId: 3,
				icon: '🏠',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '家庭生活の仕事と役割分担',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '時間の使い方を工夫',
				categoryId: 3,
				icon: '⏰',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '生活時間の有効な使い方',
				sortOrder: s(),
			},
			{
				name: '明日の準備・持ち物チェック',
				categoryId: 3,
				icon: '✅',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'seed',
				gradeLevel: 'elementary_upper',
				subcategory: '準備',
				description: '時間割を確認し必要な持ち物を揃えた',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: 'あいさつ・言葉遣い',
				categoryId: 4,
				icon: '👋',
				basePoints: 3,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '礼儀',
				description: '時と場に応じた適切な言葉遣い',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '友達と協力して活動',
				categoryId: 4,
				icon: '🤝',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '協力',
				description: '友達と互いに信頼し学び合い助け合う',
				sortOrder: s(),
			},
			{
				name: '委員会・係活動への貢献',
				categoryId: 4,
				icon: '📋',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '特別活動',
				description: '学校での役割を主体的に果たす',
				sortOrder: s(),
			},
			{
				name: '地域の人への感謝',
				categoryId: 4,
				icon: '🙏',
				basePoints: 5,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '地域',
				description: '地域の人々に感謝し共に生きる',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '絵画・デザイン制作',
				categoryId: 5,
				icon: '🎨',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '図画工作',
				description: '感じたことを絵や立体に表す',
				sortOrder: s(),
			},
			{
				name: '工作・ものづくり',
				categoryId: 5,
				icon: '🔨',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '図画工作',
				description: '用途を考えた工作・デザイン',
				sortOrder: s(),
			},
			{
				name: '合奏・楽器練習',
				categoryId: 5,
				icon: '🎹',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '音楽',
				description: 'リコーダー等の楽器演奏の練習',
				sortOrder: s(),
			},
			{
				name: '表現・フォークダンス',
				categoryId: 5,
				icon: '💃',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '表現運動',
				description: '表現・フォークダンス',
				sortOrder: s(),
			},
			{
				name: '裁縫・布を使った制作',
				categoryId: 5,
				icon: '🧵',
				basePoints: 10,
				ageMin: 10,
				ageMax: 12,
				source: 'curriculum',
				gradeLevel: 'elementary_upper',
				subcategory: '家庭科',
				description: '手縫い・ミシンを用いた布製品の制作',
				sortOrder: s(),
			},

			// ============================
			// middle_school (13-15歳) — 中学校学習指導要領
			// ============================
			// うんどう
			{
				name: '体力トレーニング',
				categoryId: 1,
				icon: '🏋️',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '体つくり',
				description: '体つくり運動・体力を高める運動の計画と実践',
				sortOrder: s(),
			},
			{
				name: 'ランニング・陸上練習',
				categoryId: 1,
				icon: '🏃',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '陸上競技',
				description: '短距離走・長距離走・走り幅跳びなどの練習',
				sortOrder: s(),
			},
			{
				name: '水泳練習',
				categoryId: 1,
				icon: '🏊',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '水泳',
				description: 'クロール・平泳ぎ・背泳ぎの技能向上',
				sortOrder: s(),
			},
			{
				name: '球技の練習',
				categoryId: 1,
				icon: '⚽',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型の技能向上',
				sortOrder: s(),
			},
			{
				name: '武道の練習',
				categoryId: 1,
				icon: '🥋',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '武道',
				description: '柔道・剣道・相撲など伝統的な運動文化',
				sortOrder: s(),
			},
			{
				name: '部活動の練習',
				categoryId: 1,
				icon: '🏅',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '部活動',
				description: '運動部・文化部での主体的な活動',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の家庭学習',
				categoryId: 2,
				icon: '📝',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '国語',
				description: '漢字・文法・読解・作文の自主学習',
				sortOrder: s(),
			},
			{
				name: '数学の家庭学習',
				categoryId: 2,
				icon: '📐',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '数学',
				description: '方程式・関数・図形の演習',
				sortOrder: s(),
			},
			{
				name: '英語の家庭学習',
				categoryId: 2,
				icon: '🌍',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '英語',
				description: '単語・文法・リスニングの練習',
				sortOrder: s(),
			},
			{
				name: '理科の自主学習',
				categoryId: 2,
				icon: '🔬',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '理科',
				description: '実験レポート・科学的な観察記録',
				sortOrder: s(),
			},
			{
				name: '社会の自主学習',
				categoryId: 2,
				icon: '📚',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '社会',
				description: '歴史・地理・公民の調べ学習',
				sortOrder: s(),
			},
			{
				name: '読書（1時間）',
				categoryId: 2,
				icon: '📖',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '読書',
				description: '幅広いジャンルの読書・読書感想文',
				sortOrder: s(),
			},
			{
				name: 'テスト勉強',
				categoryId: 2,
				icon: '🎯',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '試験対策',
				description: '定期テストに向けた計画的な学習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '調理実習の復習',
				categoryId: 3,
				icon: '🍳',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '日常食の調理と食事の仕方',
				sortOrder: s(),
			},
			{
				name: '家事の分担・実践',
				categoryId: 3,
				icon: '🏠',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '家庭の仕事を計画的に分担する',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '衣服の管理・手入れ',
				categoryId: 3,
				icon: '👕',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '衣服の選択・手入れ・洗濯',
				sortOrder: s(),
			},
			{
				name: '健康管理・生活改善',
				categoryId: 3,
				icon: '🩺',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '保健',
				description: '健康な生活と疾病の予防',
				sortOrder: s(),
			},
			{
				name: '金銭管理の実践',
				categoryId: 3,
				icon: '💰',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術家庭',
				description: '消費生活と環境への配慮',
				sortOrder: s(),
			},
			{
				name: '明日の準備・提出物チェック',
				categoryId: 3,
				icon: '✅',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'seed',
				gradeLevel: 'middle_school',
				subcategory: '準備',
				description: '時間割・提出物・部活の準備を確認した',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: '礼儀正しい言動',
				categoryId: 4,
				icon: '🤝',
				basePoints: 3,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '礼儀',
				description: '礼儀の意義を理解し適切に行動する',
				sortOrder: s(),
			},
			{
				name: '友人との協力活動',
				categoryId: 4,
				icon: '👥',
				basePoints: 5,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '友情',
				description: '友情を深め互いに切磋琢磨する',
				sortOrder: s(),
			},
			{
				name: '地域ボランティア',
				categoryId: 4,
				icon: '🌐',
				basePoints: 15,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '社会貢献',
				description: '社会参画・勤労への意欲',
				sortOrder: s(),
			},
			{
				name: '進路について考えた',
				categoryId: 4,
				icon: '🎓',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '進路',
				description: '将来の生き方・進路選択について考える',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '美術作品の制作',
				categoryId: 5,
				icon: '🎨',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '美術',
				description: '感じ取ったことを絵や彫刻で表現する',
				sortOrder: s(),
			},
			{
				name: '音楽の練習（歌唱・器楽）',
				categoryId: 5,
				icon: '🎵',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '音楽',
				description: '歌唱・器楽の表現技能の向上',
				sortOrder: s(),
			},
			{
				name: '技術ものづくり',
				categoryId: 5,
				icon: '🔧',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '技術',
				description: '材料と加工の技術・プログラミング',
				sortOrder: s(),
			},
			{
				name: 'ダンス・創作表現',
				categoryId: 5,
				icon: '💃',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: 'ダンス',
				description: '創作ダンス・フォークダンス・現代的なリズムのダンス',
				sortOrder: s(),
			},
			{
				name: '作文・レポート執筆',
				categoryId: 5,
				icon: '✍️',
				basePoints: 10,
				ageMin: 13,
				ageMax: 15,
				source: 'curriculum',
				gradeLevel: 'middle_school',
				subcategory: '国語',
				description: '論理的な文章を書く力の育成',
				sortOrder: s(),
			},

			// ============================
			// high_school (16-18歳) — 高等学校学習指導要領
			// ============================
			// うんどう
			{
				name: '体力づくり・筋トレ',
				categoryId: 1,
				icon: '🏋️',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '体つくり',
				description: '体つくり運動・自己の体力課題に応じた運動',
				sortOrder: s(),
			},
			{
				name: 'ランニング・ジョギング',
				categoryId: 1,
				icon: '🏃',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '陸上',
				description: '陸上競技・持久走など',
				sortOrder: s(),
			},
			{
				name: '球技・スポーツ活動',
				categoryId: 1,
				icon: '⚽',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '球技',
				description: 'ゴール型・ネット型・ベースボール型の発展的な活動',
				sortOrder: s(),
			},
			{
				name: '武道・ダンス',
				categoryId: 1,
				icon: '🥋',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '武道/ダンス',
				description: '伝統的な武道またはダンスの選択',
				sortOrder: s(),
			},
			{
				name: '部活動・クラブ活動',
				categoryId: 1,
				icon: '🏅',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '部活動',
				description: '運動部・文化部での主体的な取り組み',
				sortOrder: s(),
			},
			// べんきょう
			{
				name: '国語の自主学習（高校）',
				categoryId: 2,
				icon: '📝',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国語',
				description: '現代文・古文・漢文の学習',
				sortOrder: s(),
			},
			{
				name: '数学の自主学習',
				categoryId: 2,
				icon: '📐',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '数学',
				description: '数学I/II/III/A/Bの演習',
				sortOrder: s(),
			},
			{
				name: '英語の自主学習（高校）',
				categoryId: 2,
				icon: '🌍',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '英語',
				description: '英語コミュニケーション・論理英語の学習',
				sortOrder: s(),
			},
			{
				name: '理科の自主学習（高校）',
				categoryId: 2,
				icon: '🔬',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '理科',
				description: '物理・化学・生物・地学の学習と実験',
				sortOrder: s(),
			},
			{
				name: '社会科の自主学習（高校）',
				categoryId: 2,
				icon: '📚',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '社会',
				description: '地理歴史・公民の学習',
				sortOrder: s(),
			},
			{
				name: '読書・論文読解',
				categoryId: 2,
				icon: '📖',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '読書',
				description: '多様な文章の読解・批評的な読み',
				sortOrder: s(),
			},
			{
				name: '受験勉強・模試対策',
				categoryId: 2,
				icon: '🎯',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '受験',
				description: '進路実現に向けた計画的な学習',
				sortOrder: s(),
			},
			// せいかつ
			{
				name: '食事の自立（献立・調理）',
				categoryId: 3,
				icon: '🍳',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '栄養バランスを考えた献立と調理実践',
				sortOrder: s(),
			},
			{
				name: '家事の自立的実践',
				categoryId: 3,
				icon: '🏠',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '自立した生活者として家事を計画・実践',
				dailyLimit: 2,
				sortOrder: s(),
			},
			{
				name: '金銭管理・消費行動',
				categoryId: 3,
				icon: '💰',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '消費生活・金銭管理・消費者の権利と責任',
				sortOrder: s(),
			},
			{
				name: '健康管理・ストレス対処',
				categoryId: 3,
				icon: '🩺',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '保健',
				description: '精神疾患の予防・ストレスへの対処',
				sortOrder: s(),
			},
			{
				name: '環境に配慮した生活',
				categoryId: 3,
				icon: '♻️',
				basePoints: 5,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '家庭科',
				description: '持続可能な社会を目指す生活の工夫',
				sortOrder: s(),
			},
			// こうりゅう
			{
				name: '社会貢献・ボランティア',
				categoryId: 4,
				icon: '🌐',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '社会参画',
				description: '社会参画の意識と実践',
				sortOrder: s(),
			},
			{
				name: '進路研究・キャリア設計',
				categoryId: 4,
				icon: '🎓',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '進路',
				description: '自己の在り方生き方と進路選択',
				sortOrder: s(),
			},
			{
				name: 'プレゼンテーション',
				categoryId: 4,
				icon: '🎤',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '表現',
				description: '自分の考えを論理的に伝える',
				sortOrder: s(),
			},
			{
				name: '異文化交流・国際理解',
				categoryId: 4,
				icon: '🌏',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国際',
				description: '国際理解・異文化コミュニケーション',
				sortOrder: s(),
			},
			// そうぞう
			{
				name: '美術・デザイン制作',
				categoryId: 5,
				icon: '🎨',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '美術',
				description: '主題に応じた絵画・彫刻・デザインの制作',
				sortOrder: s(),
			},
			{
				name: '音楽活動（歌唱・楽器・作曲）',
				categoryId: 5,
				icon: '🎵',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '音楽',
				description: '歌唱・器楽・創作の表現活動',
				sortOrder: s(),
			},
			{
				name: '創作文・小論文執筆',
				categoryId: 5,
				icon: '✍️',
				basePoints: 10,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '国語',
				description: '創造的な文章・論理的な小論文の執筆',
				sortOrder: s(),
			},
			{
				name: 'プログラミング・情報制作',
				categoryId: 5,
				icon: '💻',
				basePoints: 15,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '情報',
				description: 'プログラミング・情報デザイン',
				sortOrder: s(),
			},
			{
				name: '探究レポート・研究発表',
				categoryId: 5,
				icon: '📊',
				basePoints: 20,
				ageMin: 16,
				ageMax: 18,
				source: 'curriculum',
				gradeLevel: 'high_school',
				subcategory: '探究',
				description: '探究課題の研究成果をまとめ発表する',
				sortOrder: s(),
			},

			// ============================
			// 家事・生活スキル（追加活動）
			// ============================
			// 料理・食事まわり（kinder）
			{ name: 'おさらあらい', categoryId: 3, icon: '🍽️💧', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: 'お皿やコップを洗う', dailyLimit: 3, sortOrder: s() },
			{ name: 'テーブルをふく', categoryId: 3, icon: '🧽', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: '食事の前後にテーブルを拭く', dailyLimit: 3, sortOrder: s() },
			{ name: 'りょうりのおてつだい', categoryId: 3, icon: '🍳', basePoints: 8, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: '料理を手伝う', dailyLimit: 2, sortOrder: s() },
			// 料理・食事まわり（elementary以上）
			{ name: '皿洗い', categoryId: 3, icon: '🍽️', basePoints: 5, ageMin: 6, ageMax: 9, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '食事', description: '食器を洗う', dailyLimit: 3, sortOrder: s() },
			{ name: '料理する', categoryId: 3, icon: '🍳', basePoints: 8, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '食事', description: '料理を作る', sortOrder: s() },
			{ name: '献立を考える', categoryId: 3, icon: '📝', basePoints: 8, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '食事', description: '食事の献立を考える', sortOrder: s() },
			{ name: '冷蔵庫を整理する', categoryId: 3, icon: '🧊', basePoints: 5, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '食事', description: '冷蔵庫・冷凍庫の中を整理する', sortOrder: s() },

			// 洗濯まわり（kinder）
			{ name: 'せんたくものをたたむ', categoryId: 3, icon: '👕', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '洗濯', description: '洗濯物をたたむ', sortOrder: s() },
			{ name: 'せんたくものをしまう', categoryId: 3, icon: '🧺', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '洗濯', description: '洗濯物をタンスにしまう', sortOrder: s() },
			// 洗濯まわり（elementary以上）
			{ name: '洗濯物をたたむ', categoryId: 3, icon: '👕', basePoints: 3, ageMin: 6, ageMax: 9, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '洗濯物をたたむ', sortOrder: s() },
			{ name: '洗濯物を干す', categoryId: 3, icon: '🧺', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '洗濯物を干す', sortOrder: s() },
			{ name: '洗濯をする', categoryId: 3, icon: '👕🫧', basePoints: 5, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '洗濯', description: '洗濯機に洗剤を入れて洗濯する', sortOrder: s() },
			{ name: 'くつを洗う', categoryId: 3, icon: '👟💧', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '靴をブラシで洗う', sortOrder: s() },

			// 掃除・片付け（kinder）
			{ name: 'おへやをそうじする', categoryId: 3, icon: '🧹🏠', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '掃除', description: '自分の部屋やリビングを掃除する', sortOrder: s() },
			{ name: 'くつをそろえる', categoryId: 3, icon: '👟', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '掃除', description: '玄関の靴をそろえる', dailyLimit: 2, sortOrder: s() },
			// 掃除・片付け（elementary以上）
			{ name: '部屋を掃除する', categoryId: 3, icon: '🧹🏠', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '掃除機をかけたり拭き掃除する', sortOrder: s() },
			{ name: 'お風呂を掃除する', categoryId: 3, icon: '🛁🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '浴槽や床を洗う', sortOrder: s() },
			{ name: 'トイレを掃除する', categoryId: 3, icon: '🚽🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: 'トイレの便器や床を掃除する', sortOrder: s() },
			{ name: '洗面台を掃除する', categoryId: 3, icon: '🪥🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '洗面台のボウルや鏡を掃除する', sortOrder: s() },
			{ name: '玄関を掃除する', categoryId: 3, icon: '🚪🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '玄関の掃き掃除や靴の片付け', sortOrder: s() },
			{ name: 'ゴミを出す', categoryId: 3, icon: '🗑️', basePoints: 3, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: 'ゴミをまとめて収集場所に出す', sortOrder: s() },

			// 生活・その他
			{ name: 'おふとんをたたむ', categoryId: 3, icon: '🛏️', basePoints: 3, ageMin: 3, ageMax: 18, source: 'seed', gradeLevel: 'kinder', subcategory: '生活', description: '起きた後に布団を畳む', sortOrder: s() },
			{ name: 'かいものにいく', categoryId: 3, icon: '🛒', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '買い物', description: '家族と一緒に買い物に行く', sortOrder: s() },
			{ name: '買い物をする', categoryId: 3, icon: '🛒', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '買い物', description: '食材や日用品の買い物をする', sortOrder: s() },
			{ name: '水やりをする', categoryId: 3, icon: '🌱💧', basePoints: 3, ageMin: 3, ageMax: 18, source: 'seed', gradeLevel: 'kinder', subcategory: '生活', description: '植物や花に水をあげる', dailyLimit: 2, sortOrder: s() },
			{ name: 'おたよりをわたす', categoryId: 3, icon: '📨', basePoints: 3, ageMin: 3, ageMax: 9, source: 'seed', gradeLevel: 'kinder', subcategory: '準備', description: '保育園・学校からの手紙を親に渡す', sortOrder: s() },
		];

		db.insert(schema.activities).values(activitiesData).run();
		console.log(`  ✓ activities: ${activitiesData.length} items (学習指導要領準拠 + 家事スキル)`);
	} else {
		// 既存DBに家事活動が未追加の場合、追加する
		const existingNames = new Set(existingActivities.map((a) => a.name));
		const choreActivities: (typeof schema.activities.$inferInsert)[] = [
			{ name: 'おさらあらい', categoryId: 3, icon: '🍽️💧', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: 'お皿やコップを洗う', dailyLimit: 3, sortOrder: 200 },
			{ name: 'テーブルをふく', categoryId: 3, icon: '🧽', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: '食事の前後にテーブルを拭く', dailyLimit: 3, sortOrder: 201 },
			{ name: 'りょうりのおてつだい', categoryId: 3, icon: '🍳', basePoints: 8, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '食事', description: '料理を手伝う', dailyLimit: 2, sortOrder: 202 },
			{ name: '皿洗い', categoryId: 3, icon: '🍽️', basePoints: 5, ageMin: 6, ageMax: 9, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '食事', description: '食器を洗う', dailyLimit: 3, sortOrder: 203 },
			{ name: '料理する', categoryId: 3, icon: '🍳', basePoints: 8, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '食事', description: '料理を作る', sortOrder: 204 },
			{ name: '献立を考える', categoryId: 3, icon: '📝', basePoints: 8, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '食事', description: '食事の献立を考える', sortOrder: 205 },
			{ name: '冷蔵庫を整理する', categoryId: 3, icon: '🧊', basePoints: 5, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '食事', description: '冷蔵庫・冷凍庫の中を整理する', sortOrder: 206 },
			{ name: 'せんたくものをたたむ', categoryId: 3, icon: '👕', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '洗濯', description: '洗濯物をたたむ', sortOrder: 207 },
			{ name: 'せんたくものをしまう', categoryId: 3, icon: '🧺', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '洗濯', description: '洗濯物をタンスにしまう', sortOrder: 208 },
			{ name: '洗濯物をたたむ', categoryId: 3, icon: '👕', basePoints: 3, ageMin: 6, ageMax: 9, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '洗濯物をたたむ', sortOrder: 209 },
			{ name: '洗濯物を干す', categoryId: 3, icon: '🧺', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '洗濯物を干す', sortOrder: 210 },
			{ name: '洗濯をする', categoryId: 3, icon: '👕🫧', basePoints: 5, ageMin: 10, ageMax: 18, source: 'seed', gradeLevel: 'elementary_upper', subcategory: '洗濯', description: '洗濯機に洗剤を入れて洗濯する', sortOrder: 211 },
			{ name: 'くつを洗う', categoryId: 3, icon: '👟💧', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '洗濯', description: '靴をブラシで洗う', sortOrder: 212 },
			{ name: 'おへやをそうじする', categoryId: 3, icon: '🧹🏠', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '掃除', description: '自分の部屋やリビングを掃除する', sortOrder: 213 },
			{ name: 'くつをそろえる', categoryId: 3, icon: '👟', basePoints: 3, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '掃除', description: '玄関の靴をそろえる', dailyLimit: 2, sortOrder: 214 },
			{ name: '部屋を掃除する', categoryId: 3, icon: '🧹🏠', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '掃除機をかけたり拭き掃除する', sortOrder: 215 },
			{ name: 'お風呂を掃除する', categoryId: 3, icon: '🛁🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '浴槽や床を洗う', sortOrder: 216 },
			{ name: 'トイレを掃除する', categoryId: 3, icon: '🚽🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: 'トイレの便器や床を掃除する', sortOrder: 217 },
			{ name: '洗面台を掃除する', categoryId: 3, icon: '🪥🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '洗面台のボウルや鏡を掃除する', sortOrder: 218 },
			{ name: '玄関を掃除する', categoryId: 3, icon: '🚪🧹', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: '玄関の掃き掃除や靴の片付け', sortOrder: 219 },
			{ name: 'ゴミを出す', categoryId: 3, icon: '🗑️', basePoints: 3, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '掃除', description: 'ゴミをまとめて収集場所に出す', sortOrder: 220 },
			{ name: 'おふとんをたたむ', categoryId: 3, icon: '🛏️', basePoints: 3, ageMin: 3, ageMax: 18, source: 'seed', gradeLevel: 'kinder', subcategory: '生活', description: '起きた後に布団を畳む', sortOrder: 221 },
			{ name: 'かいものにいく', categoryId: 3, icon: '🛒', basePoints: 5, ageMin: 3, ageMax: 5, source: 'seed', gradeLevel: 'kinder', subcategory: '買い物', description: '家族と一緒に買い物に行く', sortOrder: 222 },
			{ name: '買い物をする', categoryId: 3, icon: '🛒', basePoints: 5, ageMin: 6, ageMax: 18, source: 'seed', gradeLevel: 'elementary_lower', subcategory: '買い物', description: '食材や日用品の買い物をする', sortOrder: 223 },
			{ name: '水やりをする', categoryId: 3, icon: '🌱💧', basePoints: 3, ageMin: 3, ageMax: 18, source: 'seed', gradeLevel: 'kinder', subcategory: '生活', description: '植物や花に水をあげる', dailyLimit: 2, sortOrder: 224 },
			{ name: 'おたよりをわたす', categoryId: 3, icon: '📨', basePoints: 3, ageMin: 3, ageMax: 9, source: 'seed', gradeLevel: 'kinder', subcategory: '準備', description: '保育園・学校からの手紙を親に渡す', sortOrder: 225 },
		];
		const newActivities = choreActivities.filter((a) => !existingNames.has(a.name));
		if (newActivities.length > 0) {
			db.insert(schema.activities).values(newActivities).run();
			console.log(`  ✓ activities: added ${newActivities.length} new chore activities`);
		} else {
			console.log('  - activities: already seeded (including chores)');
		}
	}

	// ============================================================
	// 初期市場ベンチマーク（3〜12歳）
	// ============================================================
	// ベンチマークデータ設計根拠:
	// - せいかつ(3): 日常習慣は幼児期から蓄積が早く、全年齢で最高値
	// - うんどう(1): 粗大運動→巧緻運動と着実に発達（文科省体力テスト参考）
	// - べんきょう(2): 就学前は低め、6歳(小学校入学)以降に加速（学習指導要領準拠）
	// - こうりゅう(4): 幼児期は基礎的、学童期にピアグループ形成で加速
	// - そうぞう(5): 幼児期に豊かな想像力、学童期は型の習得期で緩やか
	// stdDevは平均の28-33%（年齢が上がるほど個人差拡大）
	const S = '発達段階モデル推定';
	const benchmarksData: (typeof schema.marketBenchmarks.$inferInsert)[] = [
		// age 3 (maxValue: 200) — 基本的生活習慣の形成期
		{ age: 3, categoryId: 1, mean: 16.0, stdDev: 5.0, source: S },
		{ age: 3, categoryId: 2, mean: 8.0, stdDev: 3.0, source: S },
		{ age: 3, categoryId: 3, mean: 22.0, stdDev: 6.0, source: S },
		{ age: 3, categoryId: 4, mean: 12.0, stdDev: 4.0, source: S },
		{ age: 3, categoryId: 5, mean: 14.0, stdDev: 4.5, source: S },
		// age 4 (maxValue: 350) — 運動機能の発達・社会性の芽生え
		{ age: 4, categoryId: 1, mean: 30.0, stdDev: 9.0, source: S },
		{ age: 4, categoryId: 2, mean: 18.0, stdDev: 6.0, source: S },
		{ age: 4, categoryId: 3, mean: 38.0, stdDev: 10.0, source: S },
		{ age: 4, categoryId: 4, mean: 24.0, stdDev: 8.0, source: S },
		{ age: 4, categoryId: 5, mean: 28.0, stdDev: 8.0, source: S },
		// age 5 (maxValue: 500) — 就学準備期・協調性の発達
		{ age: 5, categoryId: 1, mean: 52.0, stdDev: 15.0, source: S },
		{ age: 5, categoryId: 2, mean: 32.0, stdDev: 10.0, source: S },
		{ age: 5, categoryId: 3, mean: 60.0, stdDev: 16.0, source: S },
		{ age: 5, categoryId: 4, mean: 40.0, stdDev: 12.0, source: S },
		{ age: 5, categoryId: 5, mean: 42.0, stdDev: 12.0, source: S },
		// age 6 (maxValue: 800) — 小学校入学・学習活動の開始
		{ age: 6, categoryId: 1, mean: 85.0, stdDev: 25.0, source: S },
		{ age: 6, categoryId: 2, mean: 65.0, stdDev: 20.0, source: S },
		{ age: 6, categoryId: 3, mean: 95.0, stdDev: 25.0, source: S },
		{ age: 6, categoryId: 4, mean: 62.0, stdDev: 18.0, source: S },
		{ age: 6, categoryId: 5, mean: 58.0, stdDev: 17.0, source: S },
		// age 7 (maxValue: 1100) — 学習習慣の定着・友人関係の深化
		{ age: 7, categoryId: 1, mean: 122.0, stdDev: 36.0, source: S },
		{ age: 7, categoryId: 2, mean: 105.0, stdDev: 32.0, source: S },
		{ age: 7, categoryId: 3, mean: 138.0, stdDev: 36.0, source: S },
		{ age: 7, categoryId: 4, mean: 95.0, stdDev: 28.0, source: S },
		{ age: 7, categoryId: 5, mean: 82.0, stdDev: 24.0, source: S },
		// age 8 (maxValue: 1500) — 論理的思考の発達・ギャングエイジ
		{ age: 8, categoryId: 1, mean: 168.0, stdDev: 50.0, source: S },
		{ age: 8, categoryId: 2, mean: 152.0, stdDev: 46.0, source: S },
		{ age: 8, categoryId: 3, mean: 188.0, stdDev: 48.0, source: S },
		{ age: 8, categoryId: 4, mean: 140.0, stdDev: 42.0, source: S },
		{ age: 8, categoryId: 5, mean: 112.0, stdDev: 33.0, source: S },
		// age 9 (maxValue: 2000) — 抽象的思考・集団活動の充実
		{ age: 9, categoryId: 1, mean: 222.0, stdDev: 66.0, source: S },
		{ age: 9, categoryId: 2, mean: 205.0, stdDev: 62.0, source: S },
		{ age: 9, categoryId: 3, mean: 248.0, stdDev: 62.0, source: S },
		{ age: 9, categoryId: 4, mean: 192.0, stdDev: 58.0, source: S },
		{ age: 9, categoryId: 5, mean: 148.0, stdDev: 44.0, source: S },
		// age 10 (maxValue: 2500) — 自律性の確立・高次思考力
		{ age: 10, categoryId: 1, mean: 282.0, stdDev: 85.0, source: S },
		{ age: 10, categoryId: 2, mean: 265.0, stdDev: 80.0, source: S },
		{ age: 10, categoryId: 3, mean: 315.0, stdDev: 78.0, source: S },
		{ age: 10, categoryId: 4, mean: 248.0, stdDev: 75.0, source: S },
		{ age: 10, categoryId: 5, mean: 192.0, stdDev: 58.0, source: S },
		// age 11 (maxValue: 3000) — 思春期前期・自己表現の発達
		{ age: 11, categoryId: 1, mean: 348.0, stdDev: 105.0, source: S },
		{ age: 11, categoryId: 2, mean: 330.0, stdDev: 100.0, source: S },
		{ age: 11, categoryId: 3, mean: 390.0, stdDev: 95.0, source: S },
		{ age: 11, categoryId: 4, mean: 308.0, stdDev: 92.0, source: S },
		{ age: 11, categoryId: 5, mean: 245.0, stdDev: 74.0, source: S },
		// age 12 (maxValue: 3500) — 思春期・自立と協働
		{ age: 12, categoryId: 1, mean: 418.0, stdDev: 125.0, source: S },
		{ age: 12, categoryId: 2, mean: 400.0, stdDev: 120.0, source: S },
		{ age: 12, categoryId: 3, mean: 470.0, stdDev: 115.0, source: S },
		{ age: 12, categoryId: 4, mean: 372.0, stdDev: 112.0, source: S },
		{ age: 12, categoryId: 5, mean: 302.0, stdDev: 90.0, source: S },
	];

	let benchmarkInserted = 0;
	for (const row of benchmarksData) {
		const existing = db
			.select({ id: schema.marketBenchmarks.id })
			.from(schema.marketBenchmarks)
			.where(
				and(
					eq(schema.marketBenchmarks.age, row.age!),
					eq(schema.marketBenchmarks.categoryId, row.categoryId!),
				),
			)
			.get();
		if (!existing) {
			db.insert(schema.marketBenchmarks).values(row).run();
			benchmarkInserted++;
		}
	}
	if (benchmarkInserted > 0) {
		console.log(`  ✓ market_benchmarks: ${benchmarkInserted} items added`);
	} else {
		console.log('  - market_benchmarks: already seeded');
	}

	// ============================================================
	// 初期ステータス（おじょうさま・市場平均値で初期化）
	// ============================================================
	const existingStatuses = db.select().from(schema.statuses).all();
	if (existingStatuses.length === 0) {
		const allChildren = db.select().from(schema.children).all();
		const statusesData: (typeof schema.statuses.$inferInsert)[] = [];
		const baseValues: Record<number, number> = {
			1: 30.0, 2: 20.0, 3: 35.0, 4: 25.0, 5: 25.0,
		};
		for (const child of allChildren) {
			for (const catId of [1, 2, 3, 4, 5]) {
				statusesData.push({ childId: child.id, categoryId: catId, value: baseValues[catId] });
			}
		}

		db.insert(schema.statuses).values(statusesData).run();
		console.log(`  ✓ statuses: ${statusesData.length} items (${allChildren.length} children × 5 categories)`);
	} else {
		console.log('  - statuses: already seeded');
	}

	// ============================================================
	// 初期実績マスタ（マイルストーン型 + ライフイベント）
	// ============================================================
	const existingAchievements = db.select().from(schema.achievements).all();
	if (existingAchievements.length === 0) {
		const achievementsData: (typeof schema.achievements.$inferInsert)[] = [
			// --- はじめのいっぽ（一度きり） ---
			{
				code: 'first_step',
				name: 'はじめのいっぽ',
				description: 'はじめてかつどうをきろくした！',
				icon: '🌟',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 1,
				bonusPoints: 10,
				rarity: 'common',
				sortOrder: 1,
				repeatable: 0,
			},
			// --- れんぞくチャレンジ（繰り返し・マイルストーン） ---
			{
				code: 'streak_master',
				name: 'れんぞくチャレンジ',
				description: 'まいにちれんぞくでかつどうしよう！',
				icon: '🔥',
				category: null,
				conditionType: 'streak_days',
				conditionValue: 3,
				bonusPoints: 10,
				rarity: 'common',
				sortOrder: 2,
				repeatable: 1,
				milestoneValues: JSON.stringify([3, 5, 7, 10, 14, 21, 30, 60, 90, 180, 365]),
			},
			// --- かつどうマスター（繰り返し・マイルストーン） ---
			{
				code: 'activity_master',
				name: 'かつどうマスター',
				description: 'たくさんかつどうをきろくしよう！',
				icon: '📝',
				category: null,
				conditionType: 'total_activities',
				conditionValue: 10,
				bonusPoints: 10,
				rarity: 'common',
				sortOrder: 3,
				repeatable: 1,
				milestoneValues: JSON.stringify([10, 20, 30, 50, 100, 200, 500, 1000]),
			},
			// --- カテゴリたんけんか（繰り返し・マイルストーン） ---
			{
				code: 'category_scout',
				name: 'カテゴリたんけんか',
				description: 'いろんなカテゴリのかつどうをやってみよう！',
				icon: '🧭',
				category: null,
				conditionType: 'category_complete',
				conditionValue: 2,
				bonusPoints: 15,
				rarity: 'common',
				sortOrder: 4,
				repeatable: 1,
				milestoneValues: JSON.stringify([2, 3, 5]),
			},
			// --- カテゴリたんけん（一度きり） ---
			{
				code: 'category_explorer',
				name: 'カテゴリたんけん',
				description: '1にちでぜんぶのカテゴリをきろくした！',
				icon: '🌈',
				category: null,
				conditionType: 'all_categories',
				conditionValue: 1,
				bonusPoints: 50,
				rarity: 'rare',
				sortOrder: 5,
				repeatable: 0,
			},
			// --- レベルアップ（繰り返し・マイルストーン） ---
			{
				code: 'level_climber',
				name: 'レベルアップ',
				description: 'レベルをあげよう！',
				icon: '⭐',
				category: null,
				conditionType: 'level_reach',
				conditionValue: 3,
				bonusPoints: 20,
				rarity: 'common',
				sortOrder: 6,
				repeatable: 1,
				milestoneValues: JSON.stringify([3, 5, 7, 10]),
			},
			// --- ポイントコレクター（繰り返し・マイルストーン） ---
			{
				code: 'point_collector',
				name: 'ポイントコレクター',
				description: 'ポイントをたくさんためよう！',
				icon: '💰',
				category: null,
				conditionType: 'total_points',
				conditionValue: 100,
				bonusPoints: 10,
				rarity: 'common',
				sortOrder: 7,
				repeatable: 1,
				milestoneValues: JSON.stringify([100, 200, 300, 500, 1000, 5000, 10000]),
			},
			// --- ライフイベント（手動付与） ---
			{
				code: 'kindergarten_grad',
				name: 'ほいくえんそつえん',
				description: 'ほいくえんをそつえんした！おめでとう！',
				icon: '🎓',
				category: null,
				conditionType: 'milestone_event',
				conditionValue: 0,
				bonusPoints: 500,
				rarity: 'legendary',
				sortOrder: 100,
				repeatable: 0,
				isMilestone: 1,
			},
			{
				code: 'elementary_grad',
				name: 'しょうがっこうそつぎょう',
				description: 'しょうがっこうをそつぎょうした！おめでとう！',
				icon: '🎓',
				category: null,
				conditionType: 'milestone_event',
				conditionValue: 0,
				bonusPoints: 1000,
				rarity: 'legendary',
				sortOrder: 101,
				repeatable: 0,
				isMilestone: 1,
			},
		];

		db.insert(schema.achievements).values(achievementsData).run();
		console.log(`  ✓ achievements: ${achievementsData.length} items (milestone-based)`);
	} else {
		console.log('  - achievements: already seeded');
	}

	// ============================================================
	// 初期称号マスタ
	// ============================================================
	const existingTitles = db.select().from(schema.titles).all();
	if (existingTitles.length === 0) {
		const titlesData: (typeof schema.titles.$inferInsert)[] = [
			{
				code: 'undou_master',
				name: 'うんどうマスター',
				description: 'うんどうのへんさちが65いじょう！',
				icon: '🏋️',
				conditionType: 'category_deviation',
				conditionValue: 65,
				conditionExtra: JSON.stringify({ categoryId: 1 }),
				rarity: 'rare',
				sortOrder: 1,
			},
			{
				code: 'benkyou_tensai',
				name: 'べんきょうの天才',
				description: 'べんきょうのへんさちが65いじょう！',
				icon: '🧠',
				conditionType: 'category_deviation',
				conditionValue: 65,
				conditionExtra: JSON.stringify({ categoryId: 2 }),
				rarity: 'rare',
				sortOrder: 2,
			},
			{
				code: 'seikatsu_tatsujin',
				name: 'せいかつの達人',
				description: 'せいかつのへんさちが65いじょう！',
				icon: '🏡',
				conditionType: 'category_deviation',
				conditionValue: 65,
				conditionExtra: JSON.stringify({ categoryId: 3 }),
				rarity: 'rare',
				sortOrder: 3,
			},
			{
				code: 'kouryuu_ou',
				name: 'こうりゅうの王',
				description: 'こうりゅうのへんさちが65いじょう！',
				icon: '👑',
				conditionType: 'category_deviation',
				conditionValue: 65,
				conditionExtra: JSON.stringify({ categoryId: 4 }),
				rarity: 'rare',
				sortOrder: 4,
			},
			{
				code: 'souzou_mahou',
				name: 'そうぞうの魔法使い',
				description: 'そうぞうのへんさちが65いじょう！',
				icon: '🪄',
				conditionType: 'category_deviation',
				conditionValue: 65,
				conditionExtra: JSON.stringify({ categoryId: 5 }),
				rarity: 'rare',
				sortOrder: 5,
			},
			{
				code: 'renzoku_oni',
				name: 'れんぞくの鬼',
				description: '30にちれんぞくでかつどうをきろくした！',
				icon: '👹',
				conditionType: 'streak_days',
				conditionValue: 30,
				rarity: 'epic',
				sortOrder: 6,
			},
			{
				code: 'all_rounder',
				name: 'オールラウンダー',
				description: 'すべてのカテゴリのへんさちが55いじょう！',
				icon: '🌟',
				conditionType: 'all_categories_deviation',
				conditionValue: 55,
				rarity: 'legendary',
				sortOrder: 7,
			},
			{
				code: 'kami_level',
				name: 'かみさまのしもべ',
				description: 'レベル10にとうたつした！',
				icon: '✨',
				conditionType: 'level_reach',
				conditionValue: 10,
				rarity: 'legendary',
				sortOrder: 8,
			},
		];

		db.insert(schema.titles).values(titlesData).run();
		console.log(`  ✓ titles: ${titlesData.length} items`);
	} else {
		console.log('  - titles: already seeded');
	}

	// NOTE: PIN設定は初回セットアップウィザード（/setup）で行う
	// settings テーブルの各キーはアプリ起動時に必要に応じて自動作成される

	// ============================================================
	// 特別報酬テンプレート（settingsにJSON保存）
	// ============================================================
	const existingTemplates = db
		.select()
		.from(schema.settings)
		.where(eq(schema.settings.key, 'reward_templates'))
		.get();
	if (!existingTemplates) {
		const templates = [
			{ title: 'テスト100てん', points: 100, icon: '🎓', category: 'academic' },
			{ title: 'しかくごうかく', points: 200, icon: '📜', category: 'academic' },
			{ title: 'うんどうかい1い', points: 150, icon: '🏆', category: 'sports' },
			{ title: 'はっぴょうかいがんばった', points: 100, icon: '🎤', category: 'social' },
			{ title: 'さくひんにゅうしょう', points: 150, icon: '🎨', category: 'creative' },
			{ title: 'おてつだいありがとう', points: 50, icon: '🙏', category: 'life' },
		];
		db.insert(schema.settings)
			.values({ key: 'reward_templates', value: JSON.stringify(templates) })
			.run();
		console.log(`  ✓ reward_templates: ${templates.length} templates`);
	} else {
		console.log('  - reward_templates: already seeded');
	}

	// ============================================================
	// きせかえアイテム（19件）
	// ============================================================
	const existingAvatarItems = db.select().from(schema.avatarItems).all();
	if (existingAvatarItems.length === 0) {
		const avatarItemsData: (typeof schema.avatarItems.$inferInsert)[] = [
			// --- background ---
			{ code: 'bg_default', name: 'しろ', category: 'background', icon: '⬜', cssValue: '#ffffff', price: 0, unlockType: 'free', rarity: 'common', sortOrder: 1 },
			{ code: 'bg_sakura', name: 'さくらいろ', category: 'background', icon: '🌸', cssValue: 'linear-gradient(135deg, #fce4ec, #f8bbd0)', price: 100, unlockType: 'purchase', rarity: 'common', sortOrder: 2 },
			{ code: 'bg_sky', name: 'そらいろ', category: 'background', icon: '☁️', cssValue: 'linear-gradient(135deg, #e3f2fd, #90caf9)', price: 100, unlockType: 'purchase', rarity: 'common', sortOrder: 3 },
			{ code: 'bg_sunset', name: 'ゆうやけ', category: 'background', icon: '🌅', cssValue: 'linear-gradient(135deg, #fff3e0, #ffcc80, #ff8a65)', price: 200, unlockType: 'purchase', rarity: 'rare', sortOrder: 4 },
			{ code: 'bg_rainbow', name: 'にじいろ', category: 'background', icon: '🌈', cssValue: 'linear-gradient(135deg, #ffcdd2, #fff9c4, #c8e6c9, #bbdefb, #e1bee7)', price: 300, unlockType: 'purchase', rarity: 'rare', sortOrder: 5 },
			{ code: 'bg_galaxy', name: 'うちゅう', category: 'background', icon: '🌌', cssValue: 'linear-gradient(135deg, #1a237e, #4a148c, #880e4f)', price: 500, unlockType: 'purchase', rarity: 'epic', sortOrder: 6 },
			{ code: 'bg_gold', name: 'おうごん', category: 'background', icon: '👑', cssValue: 'linear-gradient(135deg, #ffd54f, #ffb300, #ff8f00)', price: 500, unlockType: 'purchase', rarity: 'epic', sortOrder: 7 },
			{ code: 'bg_legend', name: 'でんせつ', category: 'background', icon: '🌟', cssValue: 'linear-gradient(135deg, #e8eaf6, #c5cae9, #9fa8da, #7986cb)', price: 0, unlockType: 'level', unlockCondition: '{"level":10}', rarity: 'legendary', sortOrder: 8 },
			// --- frame ---
			{ code: 'frame_default', name: 'ふつう', category: 'frame', icon: '⬜', cssValue: '2px solid #bdbdbd', price: 0, unlockType: 'free', rarity: 'common', sortOrder: 1 },
			{ code: 'frame_star', name: 'ほし', category: 'frame', icon: '⭐', cssValue: '3px solid #ffd700', price: 150, unlockType: 'purchase', rarity: 'common', sortOrder: 2 },
			{ code: 'frame_heart', name: 'はーと', category: 'frame', icon: '💖', cssValue: '3px solid #ff69b4', price: 150, unlockType: 'purchase', rarity: 'common', sortOrder: 3 },
			{ code: 'frame_fire', name: 'ほのお', category: 'frame', icon: '🔥', cssValue: '3px solid #ff5722', price: 300, unlockType: 'purchase', rarity: 'rare', sortOrder: 4 },
			{ code: 'frame_diamond', name: 'ダイヤ', category: 'frame', icon: '💎', cssValue: '3px solid #00bcd4', price: 500, unlockType: 'purchase', rarity: 'epic', sortOrder: 5 },
			{ code: 'frame_crown', name: 'おうかん', category: 'frame', icon: '👑', cssValue: '3px double #ffd700', price: 0, unlockType: 'level', unlockCondition: '{"level":8}', rarity: 'legendary', sortOrder: 6 },
			// --- effect ---
			{ code: 'effect_none', name: 'なし', category: 'effect', icon: '➖', cssValue: '', price: 0, unlockType: 'free', rarity: 'common', sortOrder: 1 },
			{ code: 'effect_sparkle', name: 'キラキラ', category: 'effect', icon: '✨', cssValue: 'sparkle', price: 200, unlockType: 'purchase', rarity: 'rare', sortOrder: 2 },
			{ code: 'effect_pulse', name: 'ドキドキ', category: 'effect', icon: '💓', cssValue: 'pulse', price: 200, unlockType: 'purchase', rarity: 'rare', sortOrder: 3 },
			{ code: 'effect_glow', name: 'かがやき', category: 'effect', icon: '🔆', cssValue: 'glow', price: 400, unlockType: 'purchase', rarity: 'epic', sortOrder: 4 },
			{ code: 'effect_rainbow', name: 'にじ', category: 'effect', icon: '🌈', cssValue: 'rainbow', price: 0, unlockType: 'level', unlockCondition: '{"level":7}', rarity: 'legendary', sortOrder: 5 },
		];
		for (const item of avatarItemsData) {
			db.insert(schema.avatarItems).values(item).run();
		}
		console.log(`  ✓ avatar_items: ${avatarItemsData.length} items`);
	} else {
		console.log(`  - avatar_items: already seeded (${existingAvatarItems.length})`);
	}

	console.log('Seeding complete!');
}

seed();
sqlite.close();
